INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(1,'회원가입','[NAME]님, [BRANDSITE]에 회원 가입해 주셔서 감사합니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');


INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(2,'회원탈퇴','[NAME]님 [BRANDSITE]에서 회원탈퇴 처리되었습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(3,'주문완료','[NAME]님께서 신청하신 주문이 완료되었습니다. 주문번호는 [ORDERNUMBER]입니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(4,'주문입금확인','[NAME]님 [BRANDNAME]에서 [ORDERNUMBER] 주문의 입금이 확인되었습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(5,'주문발송완료','[NAME]님 주문하신 물품의 발송이 완료 되었습니다. 구매확정 부탁 드립니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(6,'취소신청','[BRANDNAME]에서 [ORDERNUMBER] 주문을 취소 신청하셨습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(7,'취소완료','[NAME]님 주문이 취소되었습니다. 취소 주문번호는 [ORDERNUMBER] 입니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');


INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(8,'교환신청','[BRANDNAME]에서 [ORDERNUMBER] 주문의 물품을 교환 신청하셨습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(9,'반품신청','[BRANDSITE]에서 [ORDERNUMBER] 주문의 물품을 반품 신청하셨습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(10,'반품동의','[NAME]님 [BRANDSITE]에서 회원탈퇴 처리되었습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(11,'반품거부','[NAME]님께서 신청하신 주문이 완료되었습니다. 주문번호는 [ORDERNUMBER]입니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(12,'반품완료','[NAME]님 [BRANDSITE]에서 [ORDERNUMBER] 주문의 입금이 확인되었습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');


INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(13,'1:1문의답변','[NAME]님 주문하신 물품의 발송이 완료 되었습니다. 구매확정 부탁 드립니다.','100001',SYSDATE,'100001',SYSDATE,'CM01002','Y');







INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(14,'회원가입','[NAME]님, [BRANDSITE]에 회원 가입해 주셔서 감사합니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(15,'회원탈퇴','[NAME]님 [BRANDSITE]에서 회원탈퇴 처리되었습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(16,'주문완료','[NAME]님께서 신청하신 주문이 완료되었습니다. 주문번호는 [ORDERNUMBER]입니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(17,'주문입금확인','[NAME]님 [BRANDNAME]에서 [ORDERNUMBER] 주문의 입금이 확인되었습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(18,'주문발송완료','[NAME]님 주문하신 물품의 발송이 완료 되었습니다. 구매확정 부탁 드립니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(19,'취소신청','[BRANDNAME]에서 [ORDERNUMBER] 주문을 취소 신청하셨습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(20,'취소완료','[NAME]님 주문이 취소되었습니다. 취소 주문번호는 [ORDERNUMBER] 입니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(21,'교환신청','[BRANDNAME]에서 [ORDERNUMBER] 주문의 물품을 교환 신청하셨습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(22,'반품신청','[BRANDSITE]에서 [ORDERNUMBER] 주문의 물품을 반품 신청하셨습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(23,'반품동의','[NAME]님 [BRANDSITE]에서 회원탈퇴 처리되었습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(24,'반품거부','[NAME]님께서 신청하신 주문이 완료되었습니다. 주문번호는 [ORDERNUMBER]입니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(25,'반품완료','[NAME]님 [BRANDSITE]에서 [ORDERNUMBER] 주문의 입금이 확인되었습니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');

INSERT INTO TBL_AD_SMS_MNG(MNG_NO,MNG_TITLE,SMS_TXT,REGR_NO,REG_DTS,UPDR_NO,UPD_DTS,SND_CLS,AUTO_CLS)
VALUES(26,'1:1문의답변','[NAME]님 주문하신 물품의 발송이 완료 되었습니다. 구매확정 부탁 드립니다.','100001',SYSDATE,'100001',SYSDATE,'CM01001','Y');