drop sequence SEQ_ME_MEM;
CREATE SEQUENCE SEQ_ME_MEM INCREMENT BY 1 START WITH 10001 MAXVALUE 9999999 MINVALUE 10001;

drop sequence SEQ_AD_SITE;
CREATE SEQUENCE SEQ_AD_SITE INCREMENT BY 1 START WITH 10001 MAXVALUE 9999999 MINVALUE 10001;

drop sequence SEQ_ME_MEM_CMNT;
CREATE SEQUENCE SEQ_ME_MEM_CMNT INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_GD_GDS_INFO;
CREATE SEQUENCE SEQ_GD_GDS_INFO INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_ME_GRD;
CREATE SEQUENCE SEQ_ME_GRD INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_AD_SITE_POLICY;
CREATE SEQUENCE SEQ_AD_SITE_POLICY INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_CM_CNSL_MEMO;
CREATE SEQUENCE SEQ_CM_CNSL_MEMO INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_AD_USER;
CREATE SEQUENCE SEQ_AD_USER INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_CM_INTG_BOARD;
CREATE SEQUENCE SEQ_CM_INTG_BOARD INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_TBL_CM_NEWS;
CREATE SEQUENCE SEQ_TBL_CM_NEWS INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;


drop sequence SEQ_TBL_CM_MAIN;
CREATE SEQUENCE SEQ_TBL_CM_MAIN INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;



drop sequence SEQ_TBL_CM_FEATURE;
CREATE SEQUENCE SEQ_TBL_CM_FEATURE INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_OR_PAY;
CREATE SEQUENCE SEQ_OR_PAY INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_OR_ADD_PAY;
CREATE SEQUENCE SEQ_OR_ADD_PAY INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_OR_ORD_MEMO;
CREATE SEQUENCE SEQ_OR_ORD_MEMO INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;



drop sequence SEQ_CM_INTG_BOARD_CNTS;
CREATE SEQUENCE SEQ_CM_INTG_BOARD_CNTS INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;



drop sequence SEQ_CM_CNSL;
CREATE SEQUENCE SEQ_CM_CNSL INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_ME_CART;
CREATE SEQUENCE SEQ_ME_CART INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_OR_ORD;
CREATE SEQUENCE SEQ_OR_ORD INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;

drop sequence SEQ_OR_ORD_GDS;
CREATE SEQUENCE SEQ_OR_ORD_GDS INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;

drop sequence SEQ_OR_DLV_NO;
CREATE SEQUENCE SEQ_OR_DLV_NO INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;

drop sequence SEQ_OR_DLV_CST_SEQ;
CREATE SEQUENCE SEQ_OR_DLV_CST_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;

drop sequence SEQ_OR_PAY_NO;
CREATE SEQUENCE SEQ_OR_PAY_NO INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;

drop sequence SEQ_ME_MYDLV_ADDR;
CREATE SEQUENCE SEQ_ME_MYDLV_ADDR INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;

drop sequence SEQ_KCP_HIST_NO;
CREATE SEQUENCE SEQ_KCP_HIST_NO INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;


drop sequence SEQ_CM_NEWS_CONT;
CREATE SEQUENCE SEQ_CM_NEWS_CONT INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;

drop sequence SEQ_CM_WORKS_WITHUS;
CREATE SEQUENCE SEQ_CM_WORKS_WITHUS INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;

drop sequence SEQ_TBL_ST_VISIT;
CREATE SEQUENCE SEQ_TBL_ST_VISIT INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;

drop sequence SEQ_TBL_OR_CLM;
CREATE SEQUENCE SEQ_TBL_OR_CLM INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;

drop sequence SEQ_TBL_OR_CLM_GDS;
CREATE SEQUENCE SEQ_TBL_OR_CLM_GDS INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 MINVALUE 1;

drop sequence SEQ_TBL_CM_SND_MAIL;
CREATE SEQUENCE SEQ_TBL_CM_SND_MAIL INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;


drop sequence SEQ_TBL_DP_RADIO;
CREATE SEQUENCE SEQ_TBL_DP_RADIO INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_DP_AWNES;
CREATE SEQUENCE SEQ_DP_AWNES INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;


drop sequence SEQ_DP_AWNES_CONT;
CREATE SEQUENCE SEQ_DP_AWNES_CONT INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_UBI_ORDER;
CREATE SEQUENCE SEQ_UBI_ORDER INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;

drop sequence SEQ_CM_EVENT;
CREATE SEQUENCE SEQ_CM_EVENT INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;


drop sequence SEQ_TBL_AD_CATE_SEASON;
CREATE SEQUENCE SEQ_TBL_AD_CATE_SEASON INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;



drop sequence SEQ_TBL_ME_LOGIN_HIST;
CREATE SEQUENCE SEQ_TBL_ME_LOGIN_HIST INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;


drop sequence SEQ_TBL_MT_CPN;
CREATE SEQUENCE SEQ_TBL_MT_CPN INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1;