/* 코드 */
DROP TABLE TBL_AD_CD 
	CASCADE CONSTRAINTS;

/* 메뉴 */
DROP TABLE TBL_AD_MENU 
	CASCADE CONSTRAINTS;

/* 권한그룹 */
DROP TABLE TBL_AD_AUTH_GRP 
	CASCADE CONSTRAINTS;

/* 접근가능권한 */
DROP TABLE TBL_AD_ACCESS_AUTH 
	CASCADE CONSTRAINTS;

/* 사용자 */
DROP TABLE TBL_AD_USER 
	CASCADE CONSTRAINTS;

/* 사용자권한그룹 */
DROP TABLE TBL_AD_USER_AUTH_GRP 
	CASCADE CONSTRAINTS;

/* 택배사 */
DROP TABLE TBL_AD_DLV_CMP 
	CASCADE CONSTRAINTS;

/* SMS문구관리 */
DROP TABLE TBL_AD_SMS_MNG 
	CASCADE CONSTRAINTS;

/* 몰통합관리 */
DROP TABLE TBL_AD_MALL_SETTING 
	CASCADE CONSTRAINTS;

/* 파비콘 */
DROP TABLE TBL_AD_FABICON 
	CASCADE CONSTRAINTS;

/* 사이트 관리 */
DROP TABLE TBL_AD_SITE 
	CASCADE CONSTRAINTS;

/* 상품 */
DROP TABLE TBL_GD_GDS 
	CASCADE CONSTRAINTS;

/* UBI카테고리 */
DROP TABLE TBL_CT_CATEGORY 
	CASCADE CONSTRAINTS;

/* 상품추가이미지 */
DROP TABLE TBL_GD_GDS_IMG 
	CASCADE CONSTRAINTS;

/* 상품검색태그 */
DROP TABLE TBL_GD_TAG 
	CASCADE CONSTRAINTS;

/* 상품 카테고리 */
DROP TABLE TBL_GD_CATEGORY 
	CASCADE CONSTRAINTS;

/* 상품정보고시 */
DROP TABLE TBL_GD_INFO 
	CASCADE CONSTRAINTS;

/* 상품아이콘 */
DROP TABLE TBL_GD_GDS_ICON 
	CASCADE CONSTRAINTS;

/* 아이콘 */
DROP TABLE TBL_GD_ICON 
	CASCADE CONSTRAINTS;

/* 회원 */
DROP TABLE TBL_ME_MEM_INFO 
	CASCADE CONSTRAINTS;

/* 회원접속내역 */
DROP TABLE TBL_ME_LOGIN_HIST 
	CASCADE CONSTRAINTS;

/* 회원적립금내역 */
DROP TABLE TBL_ME_RESERVE 
	CASCADE CONSTRAINTS;

/* 회원장바구니 */
DROP TABLE TBL_ME_CART 
	CASCADE CONSTRAINTS;

/* 회원발급쿠폰 */
DROP TABLE TBL_ME_COUP 
	CASCADE CONSTRAINTS;

/* 회원등급 */
DROP TABLE TBL_ME_GRD 
	CASCADE CONSTRAINTS;

/* 뉴스 */
DROP TABLE TBL_CM_NEWS 
	CASCADE CONSTRAINTS;

/* 상담 */
DROP TABLE TBL_CM_CNSL 
	CASCADE CONSTRAINTS;

/* 메일발송이력 */
DROP TABLE TBL_CM_SND_MAIL 
	CASCADE CONSTRAINTS;

/* 상담덧글 */
DROP TABLE TBL_CM_CNSL_MEMO 
	CASCADE CONSTRAINTS;

/* 나의배송지 */
DROP TABLE TBL_ME_MYDLV_ADDR 
	CASCADE CONSTRAINTS;

/* 주문 */
DROP TABLE TBL_OR_ORD 
	CASCADE CONSTRAINTS;

/* 주문상품 */
DROP TABLE TBL_OR_ORD_GDS 
	CASCADE CONSTRAINTS;

/* 결제 */
DROP TABLE TBL_OR_PAY 
	CASCADE CONSTRAINTS;

/* 클레임상품 */
DROP TABLE TBL_OR_CLM_GDS 
	CASCADE CONSTRAINTS;

/* 클레임 */
DROP TABLE TBL_OR_CLM 
	CASCADE CONSTRAINTS;

/* 주문배송 */
DROP TABLE TBL_OR_ORDDVL 
	CASCADE CONSTRAINTS;

/* 신용카드결제 */
DROP TABLE TBL_OR_CRCD_CRD_PAY 
	CASCADE CONSTRAINTS;

/* 실시간계좌이체 */
DROP TABLE TBL_OR_RTM_ACCT_PAY 
	CASCADE CONSTRAINTS;

/* 배송비 */
DROP TABLE TBL_OR_DLV_CST 
	CASCADE CONSTRAINTS;

/* 클레임배송 */
DROP TABLE TBL_OR_CLMDLV 
	CASCADE CONSTRAINTS;

/* KCP전문이력 */
DROP TABLE TBL_OR_KPC_HIST 
	CASCADE CONSTRAINTS;

/* 추가결제 */
DROP TABLE TBL_OR_ADD_PAY 
	CASCADE CONSTRAINTS;

/* 상품사이즈 */
DROP TABLE TBL_GD_SIZE 
	CASCADE CONSTRAINTS;

/* 가상계좌 */
DROP TABLE TBL_OR_VRTL_ACCT_PAY 
	CASCADE CONSTRAINTS;

/* 통합게시판추가컨텐츠 */
DROP TABLE TBL_CM_INTG_BOARD_CNTS 
	CASCADE CONSTRAINTS;

/* 사용자접속내역 */
DROP TABLE TBL_AD_LOGIN_HIST 
	CASCADE CONSTRAINTS;

/* 사이트운영정책 */
DROP TABLE TBL_AD_SITE_POLICY 
	CASCADE CONSTRAINTS;

/* 뉴스노출사이트 */
DROP TABLE TBL_CM_NEWS_SITE 
	CASCADE CONSTRAINTS;

/* 통합게시판 */
DROP TABLE TBL_CM_INTG_BOARD 
	CASCADE CONSTRAINTS;

/* 통합게시판추가컨텐츠상품 */
DROP TABLE TBL_CM_BOARD_GDS 
	CASCADE CONSTRAINTS;

/* SMS발송이력 */
DROP TABLE TBL_AD_SND_SMS 
	CASCADE CONSTRAINTS;

/* 전시관리 */
DROP TABLE TBL_DP_CNTS 
	CASCADE CONSTRAINTS;
	
DROP TABLE TBL_ME_MEM_CMNT
	CASCADE CONSTRAINTS;	

/* 뉴스추가컨텐츠 */
DROP TABLE TBL_CM_NEWS_CONT 
	CASCADE CONSTRAINTS;	
	
/* 사이트 시즌설정 */
DROP TABLE TBL_AD_CATE_SEASON 
	CASCADE CONSTRAINTS;
	
	
/* 시즌 카테고리 설정 */
DROP TABLE TBL_AD_CATE_CONFIG 
	CASCADE CONSTRAINTS;
	
	

/* 코드 */
CREATE TABLE TBL_AD_CD (
	CD_NO VARCHAR2(7) NOT NULL, /* 코드번호 */
	SUP_CD_NO VARCHAR2(7), /* 상위코드번호 */
	CD_NM VARCHAR2(50), /* 코드명 */
	CD_DESC VARCHAR2(4000), /* 코드설명 */
	CD_TP CHAR(7), /* 코드유형 */
	WRK_CLS_CD CHAR(2), /* 업무분류코드 */
	PRIR NUMBER, /* 우선순위 */
	USE_YN CHAR(1) , /* 사용여부 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_CD IS '코드';

COMMENT ON COLUMN TBL_AD_CD.CD_NO IS '코드번호';

COMMENT ON COLUMN TBL_AD_CD.SUP_CD_NO IS '상위코드번호';

COMMENT ON COLUMN TBL_AD_CD.CD_NM IS '코드명';

COMMENT ON COLUMN TBL_AD_CD.CD_DESC IS '코드설명';

COMMENT ON COLUMN TBL_AD_CD.CD_TP IS '코드유형';

COMMENT ON COLUMN TBL_AD_CD.WRK_CLS_CD IS '업무분류코드';

COMMENT ON COLUMN TBL_AD_CD.PRIR IS '우선순위';

COMMENT ON COLUMN TBL_AD_CD.USE_YN IS '사용여부';

COMMENT ON COLUMN TBL_AD_CD.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_CD.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_CD.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_CD.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_AD_CD
	ON TBL_AD_CD (
		CD_NO ASC
	);

/* 메뉴 */
CREATE TABLE TBL_AD_MENU (
	MENU_NO NUMBER NOT NULL, /* 메뉴번호 */
	SUP_MENU_NO NUMBER, /* 상위메뉴번호 */
	MENU_NM VARCHAR(200), /* 메뉴명 */
	MENU_TP CHAR(7), /* 메뉴유형 */
	PAGE_URL VARCHAR2(200), /* 페이지URL */
	USE_YN CHAR(1)  NOT NULL, /* 사용여부 */
	PRIR NUMBER, /* 우선순위 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_MENU IS '메뉴';

COMMENT ON COLUMN TBL_AD_MENU.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN TBL_AD_MENU.SUP_MENU_NO IS '상위메뉴번호';

COMMENT ON COLUMN TBL_AD_MENU.MENU_NM IS '메뉴명';

COMMENT ON COLUMN TBL_AD_MENU.MENU_TP IS '메뉴유형';

COMMENT ON COLUMN TBL_AD_MENU.PAGE_URL IS '페이지URL';

COMMENT ON COLUMN TBL_AD_MENU.USE_YN IS '사용여부';

COMMENT ON COLUMN TBL_AD_MENU.PRIR IS '우선순위';

COMMENT ON COLUMN TBL_AD_MENU.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_MENU.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_MENU.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_MENU.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_AD_MENU
	ON TBL_AD_MENU (
		MENU_NO ASC
	);

/* 권한그룹 */
CREATE TABLE TBL_AD_AUTH_GRP (
	AUTH_GRP_NO NUMBER NOT NULL, /* 권한그룹번호 */
	AUTH_GRP_NM VARCHAR2(50), /* 권한그룹명 */
	USE_YN CHAR(1)  NOT NULL, /* 사용여부 */
	AUTH_GRP_DESC VARCHAR2(4000), /* 권한그룹설명 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_AUTH_GRP IS '권한그룹';

COMMENT ON COLUMN TBL_AD_AUTH_GRP.AUTH_GRP_NO IS '권한그룹번호';

COMMENT ON COLUMN TBL_AD_AUTH_GRP.AUTH_GRP_NM IS '권한그룹명';

COMMENT ON COLUMN TBL_AD_AUTH_GRP.USE_YN IS '사용여부';

COMMENT ON COLUMN TBL_AD_AUTH_GRP.AUTH_GRP_DESC IS '권한그룹설명';

COMMENT ON COLUMN TBL_AD_AUTH_GRP.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_AUTH_GRP.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_AUTH_GRP.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_AUTH_GRP.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_AD_AUTH_GRP
	ON TBL_AD_AUTH_GRP (
		AUTH_GRP_NO ASC
	);

/* 접근가능권한 */
CREATE TABLE TBL_AD_ACCESS_AUTH (
	AUTH_GRP_NO NUMBER NOT NULL, /* 권한그룹번호 */
	MENU_NO NUMBER NOT NULL, /* 메뉴번호 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	REGR_NO NUMBER, /* 등록자 */
	UPD_DTS DATE, /* 수정일시 */
	UPDR_NO NUMBER /* 수정자 */
);

COMMENT ON TABLE TBL_AD_ACCESS_AUTH IS '접근가능권한';

COMMENT ON COLUMN TBL_AD_ACCESS_AUTH.AUTH_GRP_NO IS '권한그룹번호';

COMMENT ON COLUMN TBL_AD_ACCESS_AUTH.MENU_NO IS '메뉴번호';

COMMENT ON COLUMN TBL_AD_ACCESS_AUTH.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_ACCESS_AUTH.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_ACCESS_AUTH.UPD_DTS IS '수정일시';

COMMENT ON COLUMN TBL_AD_ACCESS_AUTH.UPDR_NO IS '수정자';

/* 사용자 */
CREATE TABLE TBL_AD_USER (
	USER_NO NUMBER NOT NULL, /* 사용자번호 */
	ID VARCHAR2(20), /* 아이디 */
	PWD VARCHAR2(100), /* 패스워드 */
	USER_NM VARCHAR2(50), /* 사용자명 */
	EMAIL VARCHAR2(255), /* 이메일 */
	CP_NO VARCHAR2(255), /* 휴대폰번호 */
	USE_YN CHAR(1)  NOT NULL, /* 사용여부 */
	USER_CLS CHAR(7), /* 사용자구분 */
	CMP_NM VARCHAR2(50), /* 업체명 */
	REPR_NM VARCHAR2(50), /* 대표자명 */
	PERSON_INFO_MNGR VARCHAR2(255), /* 개인정보 관리자 */
	PERSON_INFO_MNGR_EMAIL VARCHAR2(255), /* 개인정보 관리자 이메일 */
	ZIP_CD CHAR(6), /* 우편번호 */
	ADDR VARCHAR2(255), /* 주소 */
	DTL_ADDR VARCHAR2(255), /* 상세주소 */
	TEL VARCHAR2(30), /* 전화번호 */
	FAX_NO VARCHAR2(30), /* 팩스번호 */
	BIZ_REG_NO VARCHAR2(50), /* 사업자등록번호 */
	TELE_SALES_BIZ_REG_NO VARCHAR2(50), /* 통신판매사업자등록번호 */
	BIZ_ST VARCHAR2(50), /* 업태 */
	EVENT VARCHAR2(50), /* 종목 */
	SITE_AUTH_NO VARCHAR2(50), /*사이트 권한 번호*/
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_USER IS '사용자';

COMMENT ON COLUMN TBL_AD_USER.USER_NO IS '사용자번호';

COMMENT ON COLUMN TBL_AD_USER.ID IS '아이디';

COMMENT ON COLUMN TBL_AD_USER.PWD IS '패스워드';

COMMENT ON COLUMN TBL_AD_USER.USER_NM IS '사용자명';

COMMENT ON COLUMN TBL_AD_USER.EMAIL IS '이메일';

COMMENT ON COLUMN TBL_AD_USER.CP_NO IS '휴대폰번호';

COMMENT ON COLUMN TBL_AD_USER.USE_YN IS '사용여부';

COMMENT ON COLUMN TBL_AD_USER.USER_CLS IS '사용자구분';

COMMENT ON COLUMN TBL_AD_USER.CMP_NM IS '업체명';

COMMENT ON COLUMN TBL_AD_USER.REPR_NM IS '대표자명';

COMMENT ON COLUMN TBL_AD_USER.PERSON_INFO_MNGR IS '개인정보 관리자';

COMMENT ON COLUMN TBL_AD_USER.PERSON_INFO_MNGR_EMAIL IS '개인정보 관리자 이메일';

COMMENT ON COLUMN TBL_AD_USER.ZIP_CD IS '우편번호';

COMMENT ON COLUMN TBL_AD_USER.ADDR IS '주소';

COMMENT ON COLUMN TBL_AD_USER.DTL_ADDR IS '상세주소';

COMMENT ON COLUMN TBL_AD_USER.TEL IS '전화번호';

COMMENT ON COLUMN TBL_AD_USER.FAX_NO IS '팩스번호';

COMMENT ON COLUMN TBL_AD_USER.BIZ_REG_NO IS '사업자등록번호';

COMMENT ON COLUMN TBL_AD_USER.TELE_SALES_BIZ_REG_NO IS '통신판매사업자등록번호';

COMMENT ON COLUMN TBL_AD_USER.BIZ_ST IS '업태';

COMMENT ON COLUMN TBL_AD_USER.EVENT IS '종목';

COMMENT ON COLUMN TBL_AD_USER.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_USER.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_USER.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_USER.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_AD_USER
	ON TBL_AD_USER (
		USER_NO ASC
	);

/* 사용자권한그룹 */
CREATE TABLE TBL_AD_USER_AUTH_GRP (
	USER_NO NUMBER NOT NULL, /* 사용자번호 */
	AUTH_GRP_NO NUMBER NOT NULL, /* 권한그룹번호 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_USER_AUTH_GRP IS '사용자권한그룹';

COMMENT ON COLUMN TBL_AD_USER_AUTH_GRP.USER_NO IS '사용자번호';

COMMENT ON COLUMN TBL_AD_USER_AUTH_GRP.AUTH_GRP_NO IS '권한그룹번호';

COMMENT ON COLUMN TBL_AD_USER_AUTH_GRP.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_USER_AUTH_GRP.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_USER_AUTH_GRP.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_USER_AUTH_GRP.UPD_DTS IS '수정일시';

/* 택배사 */
CREATE TABLE TBL_AD_DLV_CMP (
	DLV_CMP_NO NUMBER NOT NULL, /* 택배사번호 */
	USE_YN CHAR(1)  NOT NULL, /* 사용여부 */
	DTL_ADDR VARCHAR2(255), /* 상세주소 */
	DLV_SRCH_URL VARCHAR2(200), /* 배송조회페이지 */
	ZIP_CD CHAR(6) NOT NULL, /* 우편번호 */
	DLV_RS_PAGE VARCHAR2(200), /* 배송결과페이지 */
	CHGR_NM VARCHAR2(50), /* 담당자명 */
	FAX_NO VARCHAR2(30), /* 팩스번호 */
	TEL VARCHAR2(30), /* 전화번호 */
	ADDR VARCHAR2(255), /* 주소 */
	DLV_CMP_NM VARCHAR2(50), /* 택배사명 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_DLV_CMP IS '택배사';

COMMENT ON COLUMN TBL_AD_DLV_CMP.DLV_CMP_NO IS '택배사번호';

COMMENT ON COLUMN TBL_AD_DLV_CMP.USE_YN IS '사용여부';

COMMENT ON COLUMN TBL_AD_DLV_CMP.DTL_ADDR IS '상세주소';

COMMENT ON COLUMN TBL_AD_DLV_CMP.DLV_SRCH_URL IS '배송조회페이지';

COMMENT ON COLUMN TBL_AD_DLV_CMP.ZIP_CD IS '우편번호';

COMMENT ON COLUMN TBL_AD_DLV_CMP.DLV_RS_PAGE IS '배송결과페이지';

COMMENT ON COLUMN TBL_AD_DLV_CMP.CHGR_NM IS '담당자명';

COMMENT ON COLUMN TBL_AD_DLV_CMP.FAX_NO IS '팩스번호';

COMMENT ON COLUMN TBL_AD_DLV_CMP.TEL IS '전화번호';

COMMENT ON COLUMN TBL_AD_DLV_CMP.ADDR IS '주소';

COMMENT ON COLUMN TBL_AD_DLV_CMP.DLV_CMP_NM IS '택배사명';

COMMENT ON COLUMN TBL_AD_DLV_CMP.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_DLV_CMP.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_DLV_CMP.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_DLV_CMP.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_AD_DLV_CMP
	ON TBL_AD_DLV_CMP (
		DLV_CMP_NO ASC
	);

/* SMS문구관리 */
CREATE TABLE TBL_AD_SMS_MNG (
	MNG_NO NUMBER NOT NULL, /* 관리번호 */
	MNG_TITLE VARCHAR2(50), /* 관리제목 */
	SMS_TXT VARCHAR2(255), /* SMS내용 */
	SND_CLS CHAR(7), /* 발송주체구분 */
	AUTO_CLS CHAR(1), /* 자동여부 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_SMS_MNG IS 'SMS문구관리';

COMMENT ON COLUMN TBL_AD_SMS_MNG.MNG_NO IS '관리번호';

COMMENT ON COLUMN TBL_AD_SMS_MNG.MNG_TITLE IS '관리제목';

COMMENT ON COLUMN TBL_AD_SMS_MNG.SMS_TXT IS 'SMS내용';

COMMENT ON COLUMN TBL_AD_SMS_MNG.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_SMS_MNG.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_SMS_MNG.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_SMS_MNG.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_AD_SMS_MNG
	ON TBL_AD_SMS_MNG (
		MNG_NO ASC
	);

/* 몰통합관리 */
CREATE TABLE TBL_AD_MALL_SETTING (
	CND_FREE_DLV_AMT NUMBER, /* 조건부 무료배송 금액 */
	DLV_CST NUMBER, /* 배송비 */
	MEM_JOIN_RSV_PNT NUMBER, /* 회원가입적립포인트 */
	PNT_RSV_CLS CHAR(7), /* 포인트적립구분 */
	PNT_RSV_RT NUMBER, /* 포인트적립율/액 */
	EXP_PNT NUMBER, /* 적립예정포인트 */
	USE_MIN_PNT NUMBER, /* 사용가능제한포인트 */
	MIN_PAYPNT NUMBER, /* 최저결제포인트 */
	MAX_PAYPNT NUMBER, /* 최대결제포인트 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_MALL_SETTING IS '몰통합관리';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.CND_FREE_DLV_AMT IS '조건부 무료배송 금액';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.DLV_CST IS '배송비';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.MEM_JOIN_RSV_PNT IS '회원가입적립포인트';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.PNT_RSV_CLS IS '포인트적립구분';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.PNT_RSV_RT IS '포인트적립율/액';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.EXP_PNT IS '적립예정포인트';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.USE_MIN_PNT IS '사용가능제한포인트';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.MIN_PAYPNT IS '최저결제포인트';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.MAX_PAYPNT IS '최대결제포인트';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_MALL_SETTING.UPD_DTS IS '수정일시';

/* 파비콘 */
CREATE TABLE TBL_AD_FABICON (
	FABICON_NO NUMBER NOT NULL, /* 파비콘번호 */
	FABICON_NM VARCHAR2(50), /* 파비콘명 */
	IMG VARCHAR2(255), /* 이미지 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_FABICON IS '파비콘';

COMMENT ON COLUMN TBL_AD_FABICON.FABICON_NO IS '파비콘번호';

COMMENT ON COLUMN TBL_AD_FABICON.FABICON_NM IS '파비콘명';

COMMENT ON COLUMN TBL_AD_FABICON.IMG IS '이미지';

COMMENT ON COLUMN TBL_AD_FABICON.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_FABICON.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_FABICON.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_FABICON.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_AD_FABICON
	ON TBL_AD_FABICON (
		FABICON_NO ASC
	);

/* 사이트 관리 */
CREATE TABLE TBL_AD_SITE (
	SITE_NO NUMBER NOT NULL, /* 사이트 번호 */
	SITE_NM VARCHAR2(50), /* 사이트명 */
	SITE_DESC VARCHAR2(4000), /* 사이트설명 */
	KWD VARCHAR2(4000), /* 키워드 */
	FABICON_NM VARCHAR2(50), /* 파비콘명 */
	FABICON_IMG VARCHAR2(255), /* 파비콘이미지 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_SITE IS '사이트 관리';

COMMENT ON COLUMN TBL_AD_SITE.SITE_NO IS '사이트 번호';

COMMENT ON COLUMN TBL_AD_SITE.SITE_NM IS '사이트명';

COMMENT ON COLUMN TBL_AD_SITE.SITE_DESC IS '사이트설명';

COMMENT ON COLUMN TBL_AD_SITE.KWD IS '키워드';

COMMENT ON COLUMN TBL_AD_SITE.FABICON_NM IS '파비콘명';

COMMENT ON COLUMN TBL_AD_SITE.FABICON_IMG IS '파비콘이미지';

COMMENT ON COLUMN TBL_AD_SITE.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_SITE.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_SITE.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_SITE.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_AD_SITE
	ON TBL_AD_SITE (
		SITE_NO ASC
	);

/* 상품 */
CREATE TABLE TBL_GD_GDS (
	UBI_GDS_NO VARCHAR2(30) NOT NULL, /* UBI상품번호 */
	GDS_INFO_NO NUMBER, /* 상품정보번호 */
	GDS_STAT CHAR(7), /* 상품상태 */
	BS_DESC CLOB, /* 기본설명 */
	DTL_DESC CLOB, /* 상세설명 */
	DISP_YN CHAR(1), /* 전시여부 */
	SL_TERM_CLS CHAR(7), /* 판매기간구분 */
	SL_STR_DTM DATE, /* 판매시작일시 */
	SL_END_DTM DATE, /* 판매종료일시 */
	OOS_DTS DATE, /* 품절일시 */
	SORT_NO NUMBER, /* 기본정렬값 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_GD_GDS IS '상품';

COMMENT ON COLUMN TBL_GD_GDS.GDS_INFO_NO IS '상품정보번호';

COMMENT ON COLUMN TBL_GD_GDS.GDS_STAT IS '상품상태';

COMMENT ON COLUMN TBL_GD_GDS.BS_DESC IS '기본설명';

COMMENT ON COLUMN TBL_GD_GDS.DTL_DESC IS '상세설명';

COMMENT ON COLUMN TBL_GD_GDS.DISP_YN IS '전시여부';

COMMENT ON COLUMN TBL_GD_GDS.SL_TERM_CLS IS '판매기간구분';

COMMENT ON COLUMN TBL_GD_GDS.SL_STR_DTM IS '판매시작일시';

COMMENT ON COLUMN TBL_GD_GDS.SL_END_DTM IS '판매종료일시';

COMMENT ON COLUMN TBL_GD_GDS.OOS_DTS IS '품절일시';

COMMENT ON COLUMN TBL_GD_GDS.SORT_NO IS '기본정렬값';

COMMENT ON COLUMN TBL_GD_GDS.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_GD_GDS.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_GD_GDS.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_GD_GDS.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_GD_GDS
	ON TBL_GD_GDS (
		UBI_GDS_NO ASC
	);

/* 상품추가이미지 */
CREATE TABLE TBL_GD_GDS_IMG (
	UBI_GDS_NO VARCHAR2(30) NOT NULL, /* UBI상품번호 */
	IMG_CLS CHAR(7), /* 이미지구분 */
	IMG_URL VARCHAR2(255), /* 이미지 URL */
	PRIR NUMBER, /* 우선순위 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON COLUMN TBL_GD_GDS_IMG.UBI_GDS_NO IS 'UBI상품번호';

COMMENT ON COLUMN TBL_GD_GDS_IMG.IMG_CLS IS '이미지구분';

COMMENT ON COLUMN TBL_GD_GDS_IMG.IMG_URL IS '이미지 URL';

COMMENT ON COLUMN TBL_GD_GDS_IMG.PRIR IS '우선순위';

COMMENT ON COLUMN TBL_GD_GDS_IMG.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_GD_GDS_IMG.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_GD_GDS_IMG.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_GD_GDS_IMG.UPD_DTS IS '수정일시';

/* 상품검색태그 */
CREATE TABLE TBL_GD_TAG (
	UBI_GDS_NO VARCHAR2(30) NOT NULL, /* UBI상품번호 */
	TAG_NM VARCHAR2(50), /* 태그명 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_GD_TAG IS '상품검색태그';

COMMENT ON COLUMN TBL_GD_TAG.UBI_GDS_NO IS 'UBI상품번호';

COMMENT ON COLUMN TBL_GD_TAG.TAG_NM IS '태그명';

COMMENT ON COLUMN TBL_GD_TAG.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_GD_TAG.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_GD_TAG.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_GD_TAG.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_GD_TAG
	ON TBL_GD_TAG (
		UBI_GDS_NO ASC
	);

/* 상품 카테고리 */
CREATE TABLE TBL_GD_CATEGORY (
	UBI_GDS_NO VARCHAR2(30) NOT NULL, /* UBI상품번호 */
	CTG_NO NUMBER NOT NULL, /* 카테고리번호 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_GD_CATEGORY IS '상품 카테고리';

COMMENT ON COLUMN TBL_GD_CATEGORY.UBI_GDS_NO IS 'UBI상품번호';

COMMENT ON COLUMN TBL_GD_CATEGORY.CTG_NO IS '카테고리번호';

COMMENT ON COLUMN TBL_GD_CATEGORY.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_GD_CATEGORY.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_GD_CATEGORY.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_GD_CATEGORY.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_GD_CATEGORY
	ON TBL_GD_CATEGORY (
		UBI_GDS_NO ASC
	);

/* 상품정보고시그룹 */
CREATE TABLE TBL_GD_INFO_GRP (
	GDS_INFO_NO NUMBER NOT NULL, /* 상품정보번호 */
	GDS_INFO_NM VARCHAR2(50), /* 상품정보명 */
	USE_YN CHAR(1), /* 사용여부 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_GD_INFO_GRP IS '상품정보고시그룹';

COMMENT ON COLUMN TBL_GD_INFO_GRP.GDS_INFO_NO IS '상품정보번호';

COMMENT ON COLUMN TBL_GD_INFO_GRP.GDS_INFO_NM IS '상품정보명';

COMMENT ON COLUMN TBL_GD_INFO_GRP.USE_YN IS '사용여부';

COMMENT ON COLUMN TBL_GD_INFO_GRP.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_GD_INFO_GRP.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_GD_INFO_GRP.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_GD_INFO_GRP.UPD_DTS IS '수정일시';

/* 상품정보고시 */
CREATE TABLE TBL_GD_INFO (
	GDS_INFO_NO NUMBER, /* 상품정보번호 */
	TITLE VARCHAR2(50), /* 제목 */
	TXT VARCHAR2(500), /* 내용 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_GD_INFO IS '상품정보고시';

COMMENT ON COLUMN TBL_GD_INFO.GDS_INFO_NO IS '상품정보번호';

COMMENT ON COLUMN TBL_GD_INFO.TITLE IS '제목';

COMMENT ON COLUMN TBL_GD_INFO.TXT IS '내용';

COMMENT ON COLUMN TBL_GD_INFO.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_GD_INFO.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_GD_INFO.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_GD_INFO.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_GD_INFO
	ON TBL_GD_INFO (
		GDS_INFO_NO ASC
	);

/* 상품아이콘 */
CREATE TABLE TBL_GD_GDS_ICON (
	UBI_GDS_NO VARCHAR2(30) NOT NULL, /* UBI상품번호 */
	ICON_NO NUMBER, /* 아이콘 번호 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_GD_GDS_ICON IS '상품아이콘';

COMMENT ON COLUMN TBL_GD_GDS_ICON.UBI_GDS_NO IS 'UBI상품번호';

COMMENT ON COLUMN TBL_GD_GDS_ICON.ICON_NO IS '아이콘 번호';

COMMENT ON COLUMN TBL_GD_GDS_ICON.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_GD_GDS_ICON.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_GD_GDS_ICON.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_GD_GDS_ICON.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_GD_GDS_ICON
	ON TBL_GD_GDS_ICON (
		UBI_GDS_NO ASC
	);

/* 아이콘 */
CREATE TABLE TBL_GD_ICON (
	ICON_NO NUMBER NOT NULL, /* 아이콘번호 */
	IMG_URL VARCHAR2(255), /* 이미지 URL */
	ICON_DESC VARCHAR2(255), /* 아이콘 내용 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_GD_ICON IS '아이콘';

COMMENT ON COLUMN TBL_GD_ICON.ICON_NO IS '아이콘번호';

COMMENT ON COLUMN TBL_GD_ICON.IMG_URL IS '이미지 URL';

COMMENT ON COLUMN TBL_GD_ICON.ICON_DESC IS '아이콘 내용';

COMMENT ON COLUMN TBL_GD_ICON.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_GD_ICON.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_GD_ICON.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_GD_ICON.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_GD_ICON
	ON TBL_GD_ICON (
		ICON_NO ASC
	);

/* 회원 */
CREATE TABLE TBL_ME_MEM_INFO (
	MEM_NO NUMBER NOT NULL, /* 회원번호 */
	UBI_MEM_NO NUMBER NOT NULL, /* UBI회원번호 */
	MEM_GRD_NO NUMBER, /* 회원등급번호 */
	EMAIL VARCHAR2(255), /* 이메일 */
	PWD VARCHAR2(255), /* 비밀번호 */
	NM VARCHAR2(50), /* 이름 */
	BIRTH_DT DATE, /* 생년월일 */
	SEX CHAR(1) , /* 성별 */
	MY_SLF_CERT_YN CHAR(1) , /* 본인인증유무 */
	CP_NO VARCHAR2(255), /* 휴대폰번호 */
	MAIL_SND_YN CHAR(1) , /* 메일발송여부 */
	SMS_SND_YN CHAR(1) , /* SMS발송여부 */
	COUNTRY_CD CHAR(7), /* 국가코드 */
	SITE_NO NUMBER, /* 사이트번호 */
	WDRW_YN CHAR(1),
	WDRW_RSN_CD CHAR(7),
	WDRW_DTL_RSN VARCHAR2(4000),
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_ME_MEM_INFO IS '회원';

COMMENT ON COLUMN TBL_ME_MEM_INFO.MEM_NO IS '회원번호';

COMMENT ON COLUMN TBL_ME_MEM_INFO.UBI_MEM_NO IS 'UBI회원번호';

COMMENT ON COLUMN TBL_ME_MEM_INFO.MEM_GRD_NO IS '회원등급번호';

COMMENT ON COLUMN TBL_ME_MEM_INFO.EMAIL IS '이메일';

COMMENT ON COLUMN TBL_ME_MEM_INFO.PWD IS '비밀번호';

COMMENT ON COLUMN TBL_ME_MEM_INFO.NM IS '이름';

COMMENT ON COLUMN TBL_ME_MEM_INFO.BIRTH_DT IS '생년월일';

COMMENT ON COLUMN TBL_ME_MEM_INFO.SEX IS '성별';

COMMENT ON COLUMN TBL_ME_MEM_INFO.MY_SLF_CERT_YN IS '본인인증유무';

COMMENT ON COLUMN TBL_ME_MEM_INFO.CP_NO IS '휴대폰번호';

COMMENT ON COLUMN TBL_ME_MEM_INFO.MAIL_SND_YN IS '메일발송여부';

COMMENT ON COLUMN TBL_ME_MEM_INFO.SMS_SND_YN IS 'SMS발송여부';

COMMENT ON COLUMN TBL_ME_MEM_INFO.COUNTRY_CD IS '국가코드';

COMMENT ON COLUMN TBL_ME_MEM_INFO.SITE_NO IS '사이트번호';

COMMENT ON COLUMN TBL_ME_MEM_INFO.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_ME_MEM_INFO.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_ME_MEM_INFO.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_ME_MEM_INFO.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_ME_MEM_INFO
	ON TBL_ME_MEM_INFO (
		MEM_NO ASC,
		UBI_MEM_NO ASC
	);

/* 회원접속내역 */
CREATE TABLE TBL_ME_LOGIN_HIST (
	LOGIN_SEQ NUMBER NOT NULL, /* 로그인일련번호 */
	MEM_NO NUMBER NOT NULL, /* 회원번호 */
	UBI_MEM_NO NUMBER NOT NULL, /* UBI회원번호 */
	LOGIN_LCTN VARCHAR2(4000), /* 접속경로 */
	BRWS VARCHAR2(100), /* 브라우저 */
	SITE_NO NUMBER, /* 사이트번호 */
	LOGIN_IP VARCHAR2(100), /* 로그인IP */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_ME_LOGIN_HIST IS '회원접속내역';

COMMENT ON COLUMN TBL_ME_LOGIN_HIST.LOGIN_SEQ IS '로그인일련번호';

COMMENT ON COLUMN TBL_ME_LOGIN_HIST.MEM_NO IS '회원번호';

COMMENT ON COLUMN TBL_ME_LOGIN_HIST.UBI_MEM_NO IS 'UBI회원번호';

COMMENT ON COLUMN TBL_ME_LOGIN_HIST.LOGIN_LCTN IS '접속경로';

COMMENT ON COLUMN TBL_ME_LOGIN_HIST.BRWS IS '브라우저';

COMMENT ON COLUMN TBL_ME_LOGIN_HIST.SITE_NO IS '사이트번호';

COMMENT ON COLUMN TBL_ME_LOGIN_HIST.LOGIN_IP IS '로그인IP';

COMMENT ON COLUMN TBL_ME_LOGIN_HIST.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_ME_LOGIN_HIST.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_ME_LOGIN_HIST.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_ME_LOGIN_HIST.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_ME_LOGIN_HIST
	ON TBL_ME_LOGIN_HIST (
		LOGIN_SEQ ASC,
		MEM_NO ASC,
		UBI_MEM_NO ASC
	);

/* 회원적립금내역 */
CREATE TABLE TBL_ME_RESERVE (
	MEM_NO NUMBER NOT NULL, /* 회원번호 */
	RSV_PNT NUMBER, /* 적립포인트 */
	RSV_RSN_CD CHAR(7), /* 적립사유코드 */
	RSV_YN CHAR(1) , /* 적립구분 */
	ORD_NO NUMBER, /* 주문번호 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_ME_RESERVE IS '회원적립금내역';

COMMENT ON COLUMN TBL_ME_RESERVE.MEM_NO IS '회원번호';

COMMENT ON COLUMN TBL_ME_RESERVE.RSV_PNT IS '적립포인트';

COMMENT ON COLUMN TBL_ME_RESERVE.RSV_RSN_CD IS '적립사유코드';

COMMENT ON COLUMN TBL_ME_RESERVE.RSV_YN IS '적립구분';

COMMENT ON COLUMN TBL_ME_RESERVE.ORD_NO IS '주문번호';

COMMENT ON COLUMN TBL_ME_RESERVE.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_ME_RESERVE.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_ME_RESERVE.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_ME_RESERVE.UPD_DTS IS '수정일시';

/* 회원장바구니 */
CREATE TABLE TBL_ME_CART (
	CART_NO NUMBER NOT NULL, /* 장바구니번호 */
	MEM_NO NUMBER NOT NULL, /* 회원번호 */
	UBI_GDS_NO VARCHAR2(30), /* 상품번호 */
	QTY NUMBER, /* 수량 */
	UBI_GDS_SIZE VARCHAR2(30), /* 사이즈*/
	EMAIL VARCHAR2(255), /* 이메일*/
	IP_ADDR VARCHAR2(30),
	MEM_YN CHAR(1),
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE, /* 수정일시 */
);

COMMENT ON TABLE TBL_ME_CART IS '회원장바구니';

COMMENT ON COLUMN TBL_ME_CART.CART_NO IS '장바구니번호';

COMMENT ON COLUMN TBL_ME_CART.MEM_NO IS '회원번호';

COMMENT ON COLUMN TBL_ME_CART.UBI_GDS_NO IS '상품번호';

COMMENT ON COLUMN TBL_ME_CART.QTY IS '수량';

COMMENT ON COLUMN TBL_ME_CART.UBI_GDS_SIZE IS '수량';

COMMENT ON COLUMN TBL_ME_CART.EMAIL IS '이메일';

COMMENT ON COLUMN TBL_ME_CART.IP_ADDR IS '아이피';

COMMENT ON COLUMN TBL_ME_CART.MEM_YN IS '회원여부';

COMMENT ON COLUMN TBL_ME_CART.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_ME_CART.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_ME_CART.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_ME_CART.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX TBL_ME_CART_INDEX1 ON TBL_ME_CART (CART_NO);

/* 회원발급쿠폰 */
CREATE TABLE TBL_ME_COUP (
	MEM_NO NUMBER NOT NULL, /* 회원번호 */
	CPN_NO NUMBER, /* 쿠폰번호 */
	USE_STR_DTS DATE, /* 사용가능시작일시 */
	USE_END_TM DATE, /* 사용가능종료시간 */
	USE_YN CHAR(1) , /* 사용여부 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE, /* 수정일시 */
	UBI_MEM_NO NUMBER /* UBI회원번호 */
);

COMMENT ON TABLE TBL_ME_COUP IS '회원발급쿠폰';

COMMENT ON COLUMN TBL_ME_COUP.MEM_NO IS '회원번호';

COMMENT ON COLUMN TBL_ME_COUP.CPN_NO IS '쿠폰번호';

COMMENT ON COLUMN TBL_ME_COUP.USE_STR_DTS IS '사용가능시작일시';

COMMENT ON COLUMN TBL_ME_COUP.USE_END_TM IS '사용가능종료시간';

COMMENT ON COLUMN TBL_ME_COUP.USE_YN IS '사용여부';

COMMENT ON COLUMN TBL_ME_COUP.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_ME_COUP.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_ME_COUP.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_ME_COUP.UPD_DTS IS '수정일시';

COMMENT ON COLUMN TBL_ME_COUP.UBI_MEM_NO IS 'UBI회원번호';

/* 회원등급 */
CREATE TABLE TBL_ME_GRD (
	MEM_GRD_NO NUMBER NOT NULL, /* 회원등급번호 */
	GRD_NM VARCHAR2(50), /* 등급명 */
	DC_AMT NUMBER, /* 할인금액/할인율 */
	PNT_RSV_RT NUMBER, /* 포인트적립율 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_ME_GRD IS '회원등급';

COMMENT ON COLUMN TBL_ME_GRD.MEM_GRD_NO IS '회원등급번호';

COMMENT ON COLUMN TBL_ME_GRD.GRD_NM IS '등급명';

COMMENT ON COLUMN TBL_ME_GRD.DC_AMT IS '할인금액/할인율';

COMMENT ON COLUMN TBL_ME_GRD.PNT_RSV_RT IS '포인트적립율';

COMMENT ON COLUMN TBL_ME_GRD.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_ME_GRD.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_ME_GRD.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_ME_GRD.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_ME_GRD
	ON TBL_ME_GRD (
		MEM_GRD_NO ASC
	);

/* 뉴스 */
CREATE TABLE TBL_CM_NEWS (
	TXT_NO NUMBER NOT NULL, /* 게시물번호 */
	TITLE VARCHAR2(200), /* 제목 */
	TXT CLOB, /* 내용 */
	TXT_TP CHAR(7), /* 게시물유형 */
	TXT_CLS CHAR(7), /* 게시물구분 */
	MOV_URL VARCHAR2(255), /* 동영상주소 */
	IMG_URL VARCHAR2(255), /* 이미지 URL */
	DISP_YN CHAR(1) , /* 전시여부 */
	READ_CNT NUMBER, /* 조회수 */
	PRIR NUMBER, /* 우선순위 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_CM_NEWS IS '뉴스';

COMMENT ON COLUMN TBL_CM_NEWS.TXT_NO IS '게시물번호';

COMMENT ON COLUMN TBL_CM_NEWS.TITLE IS '제목';

COMMENT ON COLUMN TBL_CM_NEWS.TXT IS '내용';

COMMENT ON COLUMN TBL_CM_NEWS.TXT_TP IS '게시물유형';

COMMENT ON COLUMN TBL_CM_NEWS.TXT_CLS IS '게시물구분';

COMMENT ON COLUMN TBL_CM_NEWS.MOV_URL IS '동영상주소';

COMMENT ON COLUMN TBL_CM_NEWS.IMG_URL IS '이미지 URL';

COMMENT ON COLUMN TBL_CM_NEWS.DISP_YN IS '전시여부';

COMMENT ON COLUMN TBL_CM_NEWS.READ_CNT IS '조회수';

COMMENT ON COLUMN TBL_CM_NEWS.PRIR IS '우선순위';

COMMENT ON COLUMN TBL_CM_NEWS.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_CM_NEWS.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_CM_NEWS.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_CM_NEWS.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_CM_NEWS
	ON TBL_CM_NEWS (
		TXT_NO ASC
	);

/* 상담 */
CREATE TABLE TBL_CM_CNSL (
	CNSL_NO NUMBER NOT NULL, /* 상담번호 */
	MEM_NO NUMBER, /* 회원번호 */
	SITE_NO NUMBER, /* 사이트번호 */
	CNSL_TP_LCL CHAR(7), /* 상담유형대분류 */
	CNSL_TP_MCL CHAR(7), /* 상담유형중분류 */
	CNSL_STAT CHAR(7), /* 상담상태 */
	PROC_CMPL_DTS DATE, /* 처리완료일시 */
	PROC_CMPL_USRNO NUMBER, /* 처리완료자 */
	MEM_ID NUMBER, /* 회원ID */
	MEM_NM VARCHAR2(50), /* 회원이름 */
	TITLE VARCHAR2(200), /* 제목 */
	CNSL_TXT CLOB, /* 상담내용 */
	PROC_TXT CLOB, /* 처리내용 */
	ORD_NO NUMBER, /* 주문번호 */
	ORD_GDS_SEQ NUMBER, /* 주문상품일련번호 */
	UBI_GDS_NO VARCHAR2(30), /* 상품번호 */
	EMAIL VARCHAR2(255), /* 이메일 */
	EMAIL_ANS_REQ_YN CHAR(1) , /* 이메일답변요청여부 */
	TEL VARCHAR2(30), /* 전화번호 */
	REPLY_TEL_YN CHAR(1) , /* 전화답변요청여부 */
	CHGR NUMBER, /* 담당자 */
	ATCH_FILE VARCHAR2(255), /* 첨부파일 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_CM_CNSL IS '상담';

COMMENT ON COLUMN TBL_CM_CNSL.CNSL_NO IS '상담번호';

COMMENT ON COLUMN TBL_CM_CNSL.MEM_NO IS '회원번호';

COMMENT ON COLUMN TBL_CM_CNSL.SITE_NO IS '사이트번호';

COMMENT ON COLUMN TBL_CM_CNSL.CNSL_TP_LCL IS '상담유형대분류';

COMMENT ON COLUMN TBL_CM_CNSL.CNSL_TP_MCL IS '상담유형중분류';

COMMENT ON COLUMN TBL_CM_CNSL.CNSL_STAT IS '상담상태';

COMMENT ON COLUMN TBL_CM_CNSL.PROC_CMPL_DTS IS '처리완료일시';

COMMENT ON COLUMN TBL_CM_CNSL.PROC_CMPL_USRNO IS '처리완료자';

COMMENT ON COLUMN TBL_CM_CNSL.MEM_ID IS '회원ID';

COMMENT ON COLUMN TBL_CM_CNSL.MEM_NM IS '회원이름';

COMMENT ON COLUMN TBL_CM_CNSL.TITLE IS '제목';

COMMENT ON COLUMN TBL_CM_CNSL.CNSL_TXT IS '상담내용';

COMMENT ON COLUMN TBL_CM_CNSL.PROC_TXT IS '처리내용';

COMMENT ON COLUMN TBL_CM_CNSL.ORD_NO IS '주문번호';

COMMENT ON COLUMN TBL_CM_CNSL.ORD_GDS_SEQ IS '주문상품일련번호';

COMMENT ON COLUMN TBL_CM_CNSL.UBI_GDS_NO IS 'UBI상품번호';

COMMENT ON COLUMN TBL_CM_CNSL.EMAIL IS '이메일';

COMMENT ON COLUMN TBL_CM_CNSL.EMAIL_ANS_REQ_YN IS '이메일답변요청여부';

COMMENT ON COLUMN TBL_CM_CNSL.TEL IS '전화번호';

COMMENT ON COLUMN TBL_CM_CNSL.REPLY_TEL_YN IS '전화답변요청여부';

COMMENT ON COLUMN TBL_CM_CNSL.REPLY_TEL_YN IS '전화답변요청여부';

COMMENT ON COLUMN TBL_CM_CNSL.ATCH_FILE IS '첨부파일';

COMMENT ON COLUMN TBL_CM_CNSL.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_CM_CNSL.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_CM_CNSL.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_CM_CNSL.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_CM_CNSL
	ON TBL_CM_CNSL (
		CNSL_NO ASC
	);

/* 메일발송이력 */
CREATE TABLE TBL_CM_SND_MAIL (
	SND_HIST_NO NUMBER NOT NULL, /* 발송이력번호 */
	SNDR_EMAIL VARCHAR2(255), /* 발송자이메일 */
	RCVR_EMAIL VARCHAR2(255), /* 수신자이메일 */
	TMPL_URL VARCHAR2(255), /* 템플릿URL */
	TITLE VARCHAR2(200), /* 제목 */
	TXT_HTML CLOB, /* 내용HTML */
	SND_DTS DATE, /* 발송일시 */
	ATCH_FILE VARCHAR2(4000), /* 첨부파일 */
	SND_CLS CHAR(7), /* 발송주체구분 */
	RSV_TG_GB CHAR(7), /* 수신대상구분 */
	RSV_TG CHAR(7), /* 수신대상 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_CM_SND_MAIL IS '메일발송이력';

COMMENT ON COLUMN TBL_CM_SND_MAIL.SND_HIST_NO IS '발송이력번호';

COMMENT ON COLUMN TBL_CM_SND_MAIL.SNDR_EMAIL IS '발송자이메일';

COMMENT ON COLUMN TBL_CM_SND_MAIL.RCVR_EMAIL IS '수신자이메일';

COMMENT ON COLUMN TBL_CM_SND_MAIL.TMPL_URL IS '템플릿URL';

COMMENT ON COLUMN TBL_CM_SND_MAIL.TITLE IS '제목';

COMMENT ON COLUMN TBL_CM_SND_MAIL.TXT_HTML IS '내용HTML';

COMMENT ON COLUMN TBL_CM_SND_MAIL.SND_DTS IS '발송일시';

COMMENT ON COLUMN TBL_CM_SND_MAIL.ATCH_FILE IS '첨부파일';

COMMENT ON COLUMN TBL_CM_SND_MAIL.SND_CLS IS '발송주체구분';

COMMENT ON COLUMN TBL_CM_SND_MAIL.RSV_TG_GB IS '수신대상구분';

COMMENT ON COLUMN TBL_CM_SND_MAIL.RSV_TG IS '수신대상';

COMMENT ON COLUMN TBL_CM_SND_MAIL.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_CM_SND_MAIL.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_CM_SND_MAIL.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_CM_SND_MAIL.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX UQ_PK_TBL_CM_SND_MAIL
	ON TBL_CM_SND_MAIL (
		SND_HIST_NO ASC
	);

ALTER TABLE TBL_CM_SND_MAIL
	ADD
		CONSTRAINT PK_TBL_CM_SND_MAIL
		PRIMARY KEY (
			SND_HIST_NO
		);

/* 상담덧글 */
CREATE TABLE TBL_CM_CNSL_MEMO (
	CNSL_NO NUMBER NOT NULL, /* 상담번호 */
	MEMO_NO NUMBER NOT NULL, /* 덧글번호 */
	MEMO_TXT VARCHAR2(4000), /* 덧글내용 */
	WRTR_CLS CHAR(7), /* 작성주체 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_CM_CNSL_MEMO IS '상담덧글';

COMMENT ON COLUMN TBL_CM_CNSL_MEMO.CNSL_NO IS '상담번호';

COMMENT ON COLUMN TBL_CM_CNSL_MEMO.MEMO_NO IS '덧글번호';

COMMENT ON COLUMN TBL_CM_CNSL_MEMO.MEMO_TXT IS '덧글내용';

COMMENT ON COLUMN TBL_CM_CNSL_MEMO.WRTR_CLS IS '작성주체';

COMMENT ON COLUMN TBL_CM_CNSL_MEMO.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_CM_CNSL_MEMO.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_CM_CNSL_MEMO.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_CM_CNSL_MEMO.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_CM_CNSL_MEMO
	ON TBL_CM_CNSL_MEMO (
		CNSL_NO ASC,
		MEMO_NO ASC
	);

/* 나의배송지 */
CREATE TABLE TBL_ME_MYDLV_ADDR (
	DLV_ADDR_SEQ NUMBER NOT NULL, /* 배송지일련번호 */
	MEM_NO NUMBER NOT NULL, /* 회원번호 */
	ADDR_BYNM VARCHAR2(50), /* 주소별칭 */
	NM VARCHAR2(50), /* 이름 */
	TEL VARCHAR2(30), /* 전화번호 */
	CP_NO VARCHAR2(255), /* 휴대폰번호 */
	ZIP_CD CHAR(6) NOT NULL, /* 우편번호 */
	BS_ADDR VARCHAR2(255), /* 기본주소 */
	DTL_ADDR VARCHAR2(255), /* 상세주소 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE, /* 수정일시 */
	BASE_VAL_YN CHAR(1) , /* 기본값여부 */
	UBI_MEM_NO NUMBER /* UBI회원번호 */
);

COMMENT ON TABLE TBL_ME_MYDLV_ADDR IS '나의배송지';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.DLV_ADDR_SEQ IS '배송지일련번호';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.MEM_NO IS '회원번호';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.ADDR_BYNM IS '주소별칭';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.NM IS '이름';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.TEL IS '전화번호';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.CP_NO IS '휴대폰번호';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.ZIP_CD IS '우편번호';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.BS_ADDR IS '기본주소';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.DTL_ADDR IS '상세주소';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.UPD_DTS IS '수정일시';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.BASE_VAL_YN IS '기본값여부';

COMMENT ON COLUMN TBL_ME_MYDLV_ADDR.UBI_MEM_NO IS 'UBI회원번호';

CREATE UNIQUE INDEX PK_TBL_ME_MYDLV_ADDR
	ON TBL_ME_MYDLV_ADDR (
		DLV_ADDR_SEQ ASC
	);

/* 주문 */
CREATE TABLE TBL_OR_ORD (
	ORD_NO NUMBER NOT NULL, /* 주문번호 */
	MEM_NO NUMBER, /* 회원번호 */
	ORD_DTS DATE, /* 주문일시 */
	ORDR_NM VARCHAR2(50), /* 주문자명 */
	ORDR_TEL VARCHAR2(30), /* 주문자전화번호 */
	ORDR_CP VARCHAR2(255), /* 주문자휴대폰번호 */
	ORDR_EMAIL VARCHAR2(255), /* 주문자 이메일 */
	ORDR_ZIP_CD CHAR(6), /* 주문자우편번호 */
	ORDR_BS_ADDR VARCHAR2(255), /* 주문자기본주소 */
	ORDR_DTL_ADDR VARCHAR2(255), /* 주문자상세주소 */
	ORD_STAT CHAR(7), /* 주문상태 */
	RCPN_NM VARCHAR2(50), /* 수령자명 */
	RCPN_TEL_NO VARCHAR2(30), /* 수령자전화번호 */
	RCPN_CP_NO VARCHAR2(255), /* 수령자휴대폰번호 */
	RCPN_ZIP_CD CHAR(6), /* 수령자우편번호 */
	RCPN_BS_ADDR VARCHAR2(255), /* 수령자기본주소 */
	RCPN_DTL_ADDR VARCHAR2(255), /* 수령자상세주소 */
	DLV_SVC_MEMO VARCHAR2(255), /* 택배메모 */
	PAY_CMPL_DTS DATE, /* 결제완료일시 */
	MEM_ID VARCHAR2(20), /* 회원ID */
	BRWS_CLS CHAR(7), /* 브라우저구분 */
	SITE_NO NUMBER, /* 사이트번호 */
	ESCROW_DLV_YN CHAR(1), /* 에스크로 변경 여부 */
	REG_IP VARCHAR2(15), /* 등록IP */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_ORD IS '주문';

COMMENT ON COLUMN TBL_OR_ORD.ORD_NO IS '주문번호';

COMMENT ON COLUMN TBL_OR_ORD.MEM_NO IS '회원번호';

COMMENT ON COLUMN TBL_OR_ORD.ORD_DTS IS '주문일시';

COMMENT ON COLUMN TBL_OR_ORD.ORDR_NM IS '주문자명';

COMMENT ON COLUMN TBL_OR_ORD.ORDR_TEL IS '주문자전화번호';

COMMENT ON COLUMN TBL_OR_ORD.ORDR_CP IS '주문자휴대폰번호';

COMMENT ON COLUMN TBL_OR_ORD.ORDR_EMAIL IS '주문자 이메일';

COMMENT ON COLUMN TBL_OR_ORD.ORDR_ZIP_CD IS '주문자우편번호';

COMMENT ON COLUMN TBL_OR_ORD.ORDR_BS_ADDR IS '주문자기본주소';

COMMENT ON COLUMN TBL_OR_ORD.ORDR_DTL_ADDR IS '주문자상세주소';

COMMENT ON COLUMN TBL_OR_ORD.ORD_STAT IS '주문상태';

COMMENT ON COLUMN TBL_OR_ORD.RCPN_NM IS '수령자명';

COMMENT ON COLUMN TBL_OR_ORD.RCPN_TEL_NO IS '수령자전화번호';

COMMENT ON COLUMN TBL_OR_ORD.RCPN_CP_NO IS '수령자휴대폰번호';

COMMENT ON COLUMN TBL_OR_ORD.RCPN_ZIP_CD IS '수령자우편번호';

COMMENT ON COLUMN TBL_OR_ORD.RCPN_BS_ADDR IS '수령자기본주소';

COMMENT ON COLUMN TBL_OR_ORD.RCPN_DTL_ADDR IS '수령자상세주소';

COMMENT ON COLUMN TBL_OR_ORD.DLV_SVC_MEMO IS '택배메모';

COMMENT ON COLUMN TBL_OR_ORD.PAY_CMPL_DTS IS '결제완료일시';

COMMENT ON COLUMN TBL_OR_ORD.MEM_ID IS '회원ID';

COMMENT ON COLUMN TBL_OR_ORD.BRWS_CLS IS '브라우저구분';

COMMENT ON COLUMN TBL_OR_ORD.SITE_NO IS '사이트번호';

COMMENT ON COLUMN TBL_OR_ORD.REG_IP IS '등록IP';

COMMENT ON COLUMN TBL_OR_ORD.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_ORD.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_ORD.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_ORD.UPD_DTS IS '수정일시';

COMMENT ON COLUMN TBL_OR_ORD.ESCROW_DLV_YN IS '에스크로배송여부';

CREATE UNIQUE INDEX PK_TBL_OR_ORD
	ON TBL_OR_ORD (
		ORD_NO ASC
	);

/* 주문상품 */
CREATE TABLE TBL_OR_ORD_GDS (
	ORD_NO NUMBER NOT NULL, /* 주문번호 */
	ORD_GDS_SEQ NUMBER NOT NULL, /* 주문상품일련번호 */
	ORD_DLV_NO NUMBER NOT NULL, /* 주문배송번호 */
	UBI_GDS_NO VARCHAR2(30) NOT NULL, /* 상품번호 */
	UBI_GDS_NM VARCHAR2(50) NOT NULL, /* 상품명 */
	UBI_GDS_SIZE VARCHAR2(20) NOT NULL, /* 사이즈 */
	COLOR VARCHAR2(50) NOT NULL, /* 색상 */
	BRND VARCHAR2(50) NOT NULL, /* 브랜드 */
	SEASONGROUP_CODE VARCHAR2(50) NOT NULL, /* 카테고리1 */
	CATEGORY1_CODE VARCHAR2(50) NOT NULL, /* 카테고리2 */
	CATEGORY2_CODE VARCHAR2(50) NOT NULL, /* 카테고리3 */
	EXP_PNT NUMBER, /* 적립예정포인트 */
	ORD_QTY NUMBER, /* 주문수량 */
	SL_PRC NUMBER, /* 판매가 */
	ACTL_PAY_PRC NUMBER, /* 실결제가 */
	PER_ORD_STAT CHAR(7), /* 개별주문상태 */
	SL_FEE_RT NUMBER, /* 판매수수료율 */
	SND_EXP_DTS DATE, /* 발송예정일시 */
	GDS_DLV_CST_PAYWAY CHAR(7), /* 상품배송비지불방식 */
	CNCL_QTY NUMBER, /* 취소수량 */
	SND_POSB_TM DATE, /* 발송가능시간 */
	SND_CMPL_DTS DATE, /* 발송완료일시 */
	SND_CPL_NO NUMBER, /* 발송완료처리자 */
	INV_NO VARCHAR2(20), /* 송장번호 */
	DLV_CMP_NO NUMBER, /* 택배사번호 */
	MNGR_MEMO VARCHAR2(255), /* 관리자메모 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	MEM_GRD_NO NUMBER, /* 회원등급번호 */
	MEM_GRD_DC_AMT NUMBER, /* 회원등급할인금액 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_ORD_GDS IS '주문상품';

COMMENT ON COLUMN TBL_OR_ORD_GDS.ORD_NO IS '주문번호';

COMMENT ON COLUMN TBL_OR_ORD_GDS.ORD_GDS_SEQ IS '주문상품일련번호';

COMMENT ON COLUMN TBL_OR_ORD_GDS.ORD_DLV_NO IS '주문배송번호';

COMMENT ON COLUMN TBL_OR_ORD_GDS.UBI_GDS_NO IS '상품번호';

COMMENT ON COLUMN TBL_OR_ORD_GDS.UBI_GDS_NM IS '상품명';

COMMENT ON COLUMN TBL_OR_ORD_GDS.UBI_GDS_SIZE IS '사이즈';

COMMENT ON COLUMN TBL_OR_ORD_GDS.COLOR IS '색상';

COMMENT ON COLUMN TBL_OR_ORD_GDS.BRND IS '브랜드';

COMMENT ON COLUMN TBL_OR_ORD_GDS.SEASONGROUP_CODE IS '카테고리1';

COMMENT ON COLUMN TBL_OR_ORD_GDS.CATEGORY1_CODE IS '카테고리2';

COMMENT ON COLUMN TBL_OR_ORD_GDS.CATEGORY2_CODE IS '카테고리3';

COMMENT ON COLUMN TBL_OR_ORD_GDS.EXP_PNT IS '적립예정포인트';

COMMENT ON COLUMN TBL_OR_ORD_GDS.ORD_QTY IS '주문수량';

COMMENT ON COLUMN TBL_OR_ORD_GDS.SL_PRC IS '판매가';

COMMENT ON COLUMN TBL_OR_ORD_GDS.ACTL_PAY_PRC IS '실결제가';

COMMENT ON COLUMN TBL_OR_ORD_GDS.PER_ORD_STAT IS '개별주문상태';

COMMENT ON COLUMN TBL_OR_ORD_GDS.SL_FEE_RT IS '판매수수료율';

COMMENT ON COLUMN TBL_OR_ORD_GDS.SND_EXP_DTS IS '발송예정일시';

COMMENT ON COLUMN TBL_OR_ORD_GDS.GDS_DLV_CST_PAYWAY IS '상품배송비지불방식';

COMMENT ON COLUMN TBL_OR_ORD_GDS.CNCL_QTY IS '취소수량';

COMMENT ON COLUMN TBL_OR_ORD_GDS.SND_POSB_TM IS '발송가능시간';

COMMENT ON COLUMN TBL_OR_ORD_GDS.SND_CMPL_DTS IS '발송완료일시';

COMMENT ON COLUMN TBL_OR_ORD_GDS.SND_CPL_NO IS '발송완료처리자';

COMMENT ON COLUMN TBL_OR_ORD_GDS.INV_NO IS '송장번호';

COMMENT ON COLUMN TBL_OR_ORD_GDS.DLV_CMP_NO IS '택배사번호';

COMMENT ON COLUMN TBL_OR_ORD_GDS.MNGR_MEMO IS '관리자메모';

COMMENT ON COLUMN TBL_OR_ORD_GDS.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_ORD_GDS.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_ORD_GDS.MEM_GRD_NO IS '회원등급번호';

COMMENT ON COLUMN TBL_OR_ORD_GDS.MEM_GRD_DC_AMT IS '회원등급할인번호';

COMMENT ON COLUMN TBL_OR_ORD_GDS.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_ORD_GDS.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_ORD_GDS
	ON TBL_OR_ORD_GDS (
		ORD_NO ASC,
		ORD_GDS_SEQ ASC
	);

/* 결제 */
CREATE TABLE TBL_OR_PAY (
	PAY_NO NUMBER NOT NULL, /* 결제번호 */
	ORD_NO NUMBER NOT NULL, /* 주문번호 */
	CLM_NO NUMBER, /* 클레임번호 */
	CNCLTG_PAYNO NUMBER, /* 취소대상결제번호 */
	PAY_AMT NUMBER, /* 결제금액 */
	CNCL_AMT NUMBER, /* 취소금액 */
	PAY_WAY CHAR(7), /* 결제수단 */
	PAY_TP CHAR(7), /* 결제유형 */
	PAY_DTS DATE, /* 결제일시 */
	PAY_CNCL_DTS DATE, /* 결제취소일시 */
	PAY_STAT CHAR(7), /* 결제상태 */
	ORD_CLM_CLS CHAR(7), /* 주문/클레임 구분 */
	ETC VARCHAR2(4000), /* 비고 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_PAY IS '결제';

COMMENT ON COLUMN TBL_OR_PAY.PAY_NO IS '결제번호';

COMMENT ON COLUMN TBL_OR_PAY.ORD_NO IS '주문번호';

COMMENT ON COLUMN TBL_OR_PAY.CLM_NO IS '클레임번호';

COMMENT ON COLUMN TBL_OR_PAY.CNCLTG_PAYNO IS '취소대상결제번호';

COMMENT ON COLUMN TBL_OR_PAY.PAY_AMT IS '결제금액';

COMMENT ON COLUMN TBL_OR_PAY.CNCL_AMT IS '취소금액';

COMMENT ON COLUMN TBL_OR_PAY.PAY_WAY IS '결제수단';

COMMENT ON COLUMN TBL_OR_PAY.PAY_TP IS '결제유형';

COMMENT ON COLUMN TBL_OR_PAY.PAY_DTS IS '결제일시';

COMMENT ON COLUMN TBL_OR_PAY.PAY_CNCL_DTS IS '결제취소일시';

COMMENT ON COLUMN TBL_OR_PAY.PAY_STAT IS '결제상태';

COMMENT ON COLUMN TBL_OR_PAY.ORD_CLM_CLS IS '주문/클레임 구분';

COMMENT ON COLUMN TBL_OR_PAY.ETC IS '비고';

COMMENT ON COLUMN TBL_OR_PAY.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_PAY.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_PAY.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_PAY.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_PAY
	ON TBL_OR_PAY (
		PAY_NO ASC
	);

/* 클레임상품 */
CREATE TABLE TBL_OR_CLM_GDS (
	CLM_GDS_SEQ NUMBER NOT NULL, /* 클레임상품일련번호 */
	CLM_NO NUMBER NOT NULL, /* 클레임번호 */
	ORD_NO NUMBER, /* 주문번호 */
	ORD_GDS_SEQ NUMBER, /* 주문상품일련번호 */
	ORD_DLV_NO NUMBER, /* 주문배송번호 */
	CLM_QTY NUMBER NOT NULL, /* 클레임수량 */
	CLM_RSN_CD CHAR(7) NOT NULL, /* 클레임사유코드 */
	CLM_TXT VARCHAR2(255), /* 클레임내용 */
	IN_CMPL_DT DATE, /* 입고완료일자 */
	INV_NO VARCHAR2(20), /* 송장번호 */
	SND_CPL_DT DATE, /* 발송완료일자 */
	CLM_GDS_STAT CHAR(7), /* 클레임상품상태 */
	DLV_CMP_NO NUMBER, /* 택배사번호 */
	ACPT_DTS DATE, /* 접수확인일시 */
	ACPT_USR_NO NUMBER, /* 접수확인자 */
	MNGR_MEMO VARCHAR2(255), /* 관리자메모 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_CLM_GDS IS '클레임상품';

COMMENT ON COLUMN TBL_OR_CLM_GDS.CLM_GDS_SEQ IS '클레임상품일련번호';

COMMENT ON COLUMN TBL_OR_CLM_GDS.CLM_NO IS '클레임번호';

COMMENT ON COLUMN TBL_OR_CLM_GDS.ORD_NO IS '주문번호';

COMMENT ON COLUMN TBL_OR_CLM_GDS.ORD_GDS_SEQ IS '주문상품일련번호';

COMMENT ON COLUMN TBL_OR_CLM_GDS.ORD_DLV_NO IS '주문배송번호';

COMMENT ON COLUMN TBL_OR_CLM_GDS.CLM_QTY IS '클레임수량';

COMMENT ON COLUMN TBL_OR_CLM_GDS.CLM_RSN_CD IS '클레임사유코드';

COMMENT ON COLUMN TBL_OR_CLM_GDS.CLM_TXT IS '클레임내용';

COMMENT ON COLUMN TBL_OR_CLM_GDS.IN_CMPL_DT IS '입고완료일자';

COMMENT ON COLUMN TBL_OR_CLM_GDS.INV_NO IS '송장번호';

COMMENT ON COLUMN TBL_OR_CLM_GDS.SND_CPL_DT IS '발송완료일자';

COMMENT ON COLUMN TBL_OR_CLM_GDS.CLM_GDS_STAT IS '클레임상품상태';

COMMENT ON COLUMN TBL_OR_CLM_GDS.DLV_CMP_NO IS '택배사번호';

COMMENT ON COLUMN TBL_OR_CLM_GDS.ACPT_DTS IS '접수확인일시';

COMMENT ON COLUMN TBL_OR_CLM_GDS.ACPT_USR_NO IS '접수확인자';

COMMENT ON COLUMN TBL_OR_CLM_GDS.MNGR_MEMO IS '관리자메모';

COMMENT ON COLUMN TBL_OR_CLM_GDS.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_CLM_GDS.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_CLM_GDS.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_CLM_GDS.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_CLM_GDS
	ON TBL_OR_CLM_GDS (
		CLM_GDS_SEQ ASC,
		CLM_NO ASC
	);

/* 클레임 */
CREATE TABLE TBL_OR_CLM (
	CLM_NO NUMBER NOT NULL, /* 클레임번호 */
	CLM_STAT CHAR(7) NOT NULL, /* 클레임상태 */
	PROC_CMPL_DTS DATE, /* 처리완료일시 */
	ORD_NO NUMBER NOT NULL, /* 주문번호 */
	CLM_TP CHAR(7) NOT NULL, /* 클레임유형 */
	RCPN_NM VARCHAR2(50), /* 수령자명 */
	RCPN_TEL_NO VARCHAR2(30), /* 수령자전화번호 */
	RCPN_CP_NO VARCHAR2(255), /* 수령자휴대폰번호 */
	RCPN_ZIP_CD CHAR(6), /* 수령자우편번호 */
	RCPN_BS_ADDR VARCHAR2(255), /* 수령자기본주소 */
	RCPN_DTL_ADDR VARCHAR2(255), /* 수령자상세주소 */
	DLV_SVC_MEMO VARCHAR2(255), /* 택배메모 */
	RFND_ACCT_NO VARCHAR2(20), /* 환불계좌번호 */
	RFND_BNK_CD CHAR(2),  /* 환불은행코드 */
	RFND_ACCT_OWN VARCHAR2(50),  /* 환불예금주 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_CLM IS '클레임';

COMMENT ON COLUMN TBL_OR_CLM.CLM_NO IS '클레임번호';

COMMENT ON COLUMN TBL_OR_CLM.CLM_STAT IS '클레임상태';

COMMENT ON COLUMN TBL_OR_CLM.PROC_CMPL_DTS IS '처리완료일시';

COMMENT ON COLUMN TBL_OR_CLM.ORD_NO IS '주문번호';

COMMENT ON COLUMN TBL_OR_CLM.CLM_TP IS '클레임유형';

COMMENT ON COLUMN TBL_OR_CLM.RCPN_NM IS '수령자명';

COMMENT ON COLUMN TBL_OR_CLM.RCPN_TEL_NO IS '수령자전화번호';

COMMENT ON COLUMN TBL_OR_CLM.RCPN_CP_NO IS '수령자휴대폰번호';

COMMENT ON COLUMN TBL_OR_CLM.RCPN_ZIP_CD IS '수령자우편번호';

COMMENT ON COLUMN TBL_OR_CLM.RCPN_BS_ADDR IS '수령자기본주소';

COMMENT ON COLUMN TBL_OR_CLM.RCPN_DTL_ADDR IS '수령자상세주소';

COMMENT ON COLUMN TBL_OR_CLM.DLV_SVC_MEMO IS '택배메모';

COMMENT ON COLUMN TBL_OR_CLM.RFND_ACCT_NO IS '환불계좌번호';

COMMENT ON COLUMN TBL_OR_CLM.RFND_BNK_CD IS '환불은행코드';

COMMENT ON COLUMN TBL_OR_CLM.RFND_ACCT_OWN IS '환불예금주';

COMMENT ON COLUMN TBL_OR_CLM.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_CLM.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_CLM.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_CLM.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_CLM
	ON TBL_OR_CLM (
		CLM_NO ASC
	);

/* 주문배송 */
CREATE TABLE TBL_OR_ORDDVL (
	ORD_DLV_NO NUMBER NOT NULL, /* 주문배송번호 */
	ORD_NO NUMBER NOT NULL, /* 주문번호 */
	PLCY_DLV_CST NUMBER, /* 정책배송비 */
	DLV_CST_ETC VARCHAR2(255), /* 배송비비고 */
	DLV_CST_PAYWAY CHAR(7), /* 배송비지불방식 */
	MIN_ORD_AMT NUMBER, /* 기준주문금액 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_ORDDVL IS '주문배송';

COMMENT ON COLUMN TBL_OR_ORDDVL.ORD_DLV_NO IS '주문배송번호';

COMMENT ON COLUMN TBL_OR_ORDDVL.ORD_NO IS '주문번호';

COMMENT ON COLUMN TBL_OR_ORDDVL.PLCY_DLV_CST IS '정책배송비';

COMMENT ON COLUMN TBL_OR_ORDDVL.DLV_CST_ETC IS '배송비비고';

COMMENT ON COLUMN TBL_OR_ORDDVL.DLV_CST_PAYWAY IS '배송비지불방식';

COMMENT ON COLUMN TBL_OR_ORDDVL.MIN_ORD_AMT IS '기준주문금액';

COMMENT ON COLUMN TBL_OR_ORDDVL.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_ORDDVL.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_ORDDVL.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_ORDDVL.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_ORDDVL
	ON TBL_OR_ORDDVL (
		ORD_DLV_NO ASC
	);

/* 신용카드결제 */
CREATE TABLE TBL_OR_CRCD_CRD_PAY (
	PAY_NO NUMBER NOT NULL, /* 결제번호 */
	CARD_CD CHAR(4), /* 카드발급사코드 */
	CARD_NAME VARCHAR2(50), /* 카드발급사명 */
	CARD_NO VARCHAR2(16), /* 카드번호 */
	APP_NO VARCHAR2(8), /* 승인번호 */
	APP_TIME VARCHAR2(14), /* 승인시간 */
	NOINF CHAR(1), /* 무이자여부 */
	QUOTA CHAR(2), /* 할부기간 */
	AMOUNT NUMBER, /* 카드결제금액 */
	PARTCANC_YN CHAR(1) , /* 부분취소가능여부 */
	CARD_BIN_TYPE_01 CHAR(1) , /* 카드구분정보1 */
	CARD_BIN_TYPE_02 CHAR(1) , /* 카드구분정보2 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_CRCD_CRD_PAY IS '신용카드결제';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.PAY_NO IS '결제번호';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.CARD_CD IS '카드발급사코드';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.CARD_NAME IS '카드발급사명';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.CARD_NO IS '카드번호';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.APP_NO IS '승인번호';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.APP_TIME IS '승인시간';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.NOINF IS '무이자여부';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.QUOTA IS '할부기간';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.AMOUNT IS '카드결제금액';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.PARTCANC_YN IS '부분취소가능여부';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.CARD_BIN_TYPE_01 IS '카드구분정보1';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.CARD_BIN_TYPE_02 IS '카드구분정보2';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_CRCD_CRD_PAY.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_CRCD_CRD_PAY
	ON TBL_OR_CRCD_CRD_PAY (
		PAY_NO ASC
	);

/* 실시간계좌이체 */
CREATE TABLE TBL_OR_RTM_ACCT_PAY (
	PAY_NO NUMBER NOT NULL, /* 결제번호 */
	BANK_CODE CHAR(4), /* 은행코드 */
	BANK_NAME VARCHAR2(50), /* 은행명 */
	APP_TIME VARCHAR2(14), /* 결제시각 */
	CASH_AUTHNO VARCHAR2(9), /* 현금영수증승인번호 */
	AMOUNT NUMBER, /* 계좌이체결제금액 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_RTM_ACCT_PAY IS '실시간계좌이체';

COMMENT ON COLUMN TBL_OR_RTM_ACCT_PAY.PAY_NO IS '결제번호';

COMMENT ON COLUMN TBL_OR_RTM_ACCT_PAY.BANK_CODE IS '은행코드';

COMMENT ON COLUMN TBL_OR_RTM_ACCT_PAY.BANK_NAME IS '은행명';

COMMENT ON COLUMN TBL_OR_RTM_ACCT_PAY.APP_TIME IS '결제시각';

COMMENT ON COLUMN TBL_OR_RTM_ACCT_PAY.CASH_AUTHNO IS '현금영수증승인번호';

COMMENT ON COLUMN TBL_OR_RTM_ACCT_PAY.AMOUNT IS '계좌이체결제금액';

COMMENT ON COLUMN TBL_OR_RTM_ACCT_PAY.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_RTM_ACCT_PAY.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_RTM_ACCT_PAY.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_RTM_ACCT_PAY.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_RTM_ACCT_PAY
	ON TBL_OR_RTM_ACCT_PAY (
		PAY_NO ASC
	);

/* 배송비 */
CREATE TABLE TBL_OR_DLV_CST (
	DLV_CST_SEQ NUMBER NOT NULL, /* 배송비일련번호 */
	ORD_DLV_NO NUMBER NOT NULL, /* 주문배송번호 */
	CLM_NO NUMBER, /* 클레임번호 */
	ORD_CLM_CLS CHAR(7), /* 주문/클레임구분 */
	DLV_CST_TP CHAR(7), /* 배송비유형 */
	FREE_DLVRSN_CD CHAR(7), /* 무료배송사유코드 */
	ACTL_DLV_CST NUMBER, /* 실배송비 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_DLV_CST IS '배송비';

COMMENT ON COLUMN TBL_OR_DLV_CST.DLV_CST_SEQ IS '배송비일련번호';

COMMENT ON COLUMN TBL_OR_DLV_CST.ORD_DLV_NO IS '주문배송번호';

COMMENT ON COLUMN TBL_OR_DLV_CST.CLM_NO IS '클레임번호';

COMMENT ON COLUMN TBL_OR_DLV_CST.ORD_CLM_CLS IS '주문/클레임구분';

COMMENT ON COLUMN TBL_OR_DLV_CST.DLV_CST_TP IS '배송비유형';

COMMENT ON COLUMN TBL_OR_DLV_CST.FREE_DLVRSN_CD IS '무료배송사유코드';

COMMENT ON COLUMN TBL_OR_DLV_CST.ACTL_DLV_CST IS '실배송비';

COMMENT ON COLUMN TBL_OR_DLV_CST.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_DLV_CST.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_DLV_CST.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_DLV_CST.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_DLV_CST
	ON TBL_OR_DLV_CST (
		DLV_CST_SEQ ASC,
		ORD_DLV_NO ASC
	);

/* 클레임배송 */
CREATE TABLE TBL_OR_CLMDLV (
	CLM_NO NUMBER NOT NULL, /* 클레임번호 */
	ORD_DLV_NO NUMBER NOT NULL, /* 주문배송번호 */
	CLM_FLT_CD CHAR(7), /* 클레임귀책코드 */
	RTN_GDS_DLV_SVC_CST NUMBER, /* 반품택배비 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_CLMDLV IS '클레임배송';

COMMENT ON COLUMN TBL_OR_CLMDLV.CLM_NO IS '클레임번호';

COMMENT ON COLUMN TBL_OR_CLMDLV.ORD_DLV_NO IS '주문배송번호';

COMMENT ON COLUMN TBL_OR_CLMDLV.CLM_FLT_CD IS '클레임귀책코드';

COMMENT ON COLUMN TBL_OR_CLMDLV.RTN_GDS_DLV_SVC_CST IS '반품택배비';

COMMENT ON COLUMN TBL_OR_CLMDLV.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_CLMDLV.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_CLMDLV.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_CLMDLV.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_CLMDLV
	ON TBL_OR_CLMDLV (
		CLM_NO ASC,
		ORD_DLV_NO ASC
	);

/* KCP전문이력 */
CREATE TABLE TBL_OR_KPC_HIST (
	KPC_HIST_NO NUMBER NOT NULL, /* 전문이력번호 */
	ORD_NO VARCHAR2(50), /* 주문번호 */
	TNO CHAR(20), /* KCP거래번호 */
	CLM_NO NUMBER, /* 클레임번호 */
	RES_CD CHAR(4), /* 결과코드 */
	RES_MSG VARCHAR2(200), /* 결과메세지 */
	BSUCC CHAR(5), /* 자동취소 구분 */
	ESCW_YN CHAR(1) , /* 에스크로결제여부 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_KPC_HIST IS 'KCP전문이력';

COMMENT ON COLUMN TBL_OR_KPC_HIST.KPC_HIST_NO IS '전문이력번호';

COMMENT ON COLUMN TBL_OR_KPC_HIST.ORD_NO IS '주문번호';

COMMENT ON COLUMN TBL_OR_KPC_HIST.TNO IS 'KCP거래번호';

COMMENT ON COLUMN TBL_OR_KPC_HIST.CLM_NO IS '클레임번호';

COMMENT ON COLUMN TBL_OR_KPC_HIST.RES_CD IS '결과코드';

COMMENT ON COLUMN TBL_OR_KPC_HIST.RES_MSG IS '결과메세지';

COMMENT ON COLUMN TBL_OR_KPC_HIST.BSUCC IS '자동취소 구분';

COMMENT ON COLUMN TBL_OR_KPC_HIST.ESCW_YN IS '에스크로결제여부';

COMMENT ON COLUMN TBL_OR_KPC_HIST.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_KPC_HIST.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_KPC_HIST.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_KPC_HIST.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_KPC_HIST
	ON TBL_OR_KPC_HIST (
		KPC_HIST_NO ASC
	);

/* 추가결제 */
CREATE TABLE TBL_OR_ADD_PAY (
	ADD_PAY_NO NUMBER NOT NULL, /* 추가결제번호 */
	PAY_NO NUMBER NOT NULL, /* 결제번호 */
	ORD_NO NUMBER NOT NULL, /* 주문번호 */
	ADD_PAY_RSN VARCHAR2(255), /* 추가결제사유 */
	ADD_PAY_AMT NUMBER, /* 추가결제금액 */
	MEM_NO NUMBER, /* 회원번호 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_ADD_PAY IS '추가결제';

COMMENT ON COLUMN TBL_OR_ADD_PAY.ADD_PAY_NO IS '추가결제번호';

COMMENT ON COLUMN TBL_OR_ADD_PAY.PAY_NO IS '결제번호';

COMMENT ON COLUMN TBL_OR_ADD_PAY.ORD_NO IS '주문번호';

COMMENT ON COLUMN TBL_OR_ADD_PAY.ADD_PAY_RSN IS '추가결제사유';

COMMENT ON COLUMN TBL_OR_ADD_PAY.ADD_PAY_AMT IS '추가결제금액';

COMMENT ON COLUMN TBL_OR_ADD_PAY.MEM_NO IS '회원번호';

COMMENT ON COLUMN TBL_OR_ADD_PAY.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_ADD_PAY.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_ADD_PAY.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_ADD_PAY.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_ADD_PAY
	ON TBL_OR_ADD_PAY (
		ADD_PAY_NO ASC,
		PAY_NO ASC
	);

/* 상품사이즈 */
CREATE TABLE TBL_GD_SIZE (
	UBI_GDS_NO VARCHAR2(30) NOT NULL, /* UBI상품번호 */
	SIZE_NM VARCHAR2(200), /* 사이즈 이름 */
	SIZE_1 VARCHAR2(50), /* 사이즈_1 */
	SIZE_2 VARCHAR2(50), /* 사이즈_2 */
	SIZE_3 VARCHAR2(50), /* 사이즈_3 */
	SIZE_4 VARCHAR2(50), /* 사이즈_4 */
	SIZE_5 VARCHAR2(50), /* 사이즈_5 */
	SIZE_6 VARCHAR2(50), /* 사이즈_6 */
	SIZE_7 VARCHAR2(50), /* 사이즈_7 */
	SIZE_8 VARCHAR2(50), /* 사이즈_8 */
	SIZE_9 VARCHAR2(50), /* 사이즈_9 */
	SIZE_10 VARCHAR2(50) /* 사이즈_10 */
);

COMMENT ON TABLE TBL_GD_SIZE IS '상품사이즈';

COMMENT ON COLUMN TBL_GD_SIZE.UBI_GDS_NO IS 'UBI상품번호';

COMMENT ON COLUMN TBL_GD_SIZE.SIZE_NM IS '사이즈 이름';

COMMENT ON COLUMN TBL_GD_SIZE.SIZE_1 IS '사이즈_1';

COMMENT ON COLUMN TBL_GD_SIZE.SIZE_2 IS '사이즈_2';

COMMENT ON COLUMN TBL_GD_SIZE.SIZE_3 IS '사이즈_3';

COMMENT ON COLUMN TBL_GD_SIZE.SIZE_4 IS '사이즈_4';

COMMENT ON COLUMN TBL_GD_SIZE.SIZE_5 IS '사이즈_5';

COMMENT ON COLUMN TBL_GD_SIZE.SIZE_6 IS '사이즈_6';

COMMENT ON COLUMN TBL_GD_SIZE.SIZE_7 IS '사이즈_7';

COMMENT ON COLUMN TBL_GD_SIZE.SIZE_8 IS '사이즈_8';

COMMENT ON COLUMN TBL_GD_SIZE.SIZE_9 IS '사이즈_9';

COMMENT ON COLUMN TBL_GD_SIZE.SIZE_10 IS '사이즈_10';

/* 가상계좌 */
CREATE TABLE TBL_OR_VRTL_ACCT_PAY (
	PAY_NO NUMBER NOT NULL, /* 결제번호 */
	AMOUNT NUMBER, /* 가상계좌결제금액 */
	BANKCODE CHAR(4), /* 은행코드 */
	BANKNAME VARCHAR2(50), /* 은행명 */
	ACCOUNT VARCHAR2(20), /* 가상계좌번호 */
	VA_DATE VARCHAR2(14), /* 입금마감일 */
	APP_TIME VARCHAR2(14), /* 계좌발급시간 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_VRTL_ACCT_PAY IS '가상계좌';

COMMENT ON COLUMN TBL_OR_VRTL_ACCT_PAY.PAY_NO IS '결제번호';

COMMENT ON COLUMN TBL_OR_VRTL_ACCT_PAY.AMOUNT IS '가상계좌결제금액';

COMMENT ON COLUMN TBL_OR_VRTL_ACCT_PAY.BANKCODE IS '은행코드';

COMMENT ON COLUMN TBL_OR_VRTL_ACCT_PAY.BANKNAME IS '은행명';

COMMENT ON COLUMN TBL_OR_VRTL_ACCT_PAY.ACCOUNT IS '가상계좌번호';

COMMENT ON COLUMN TBL_OR_VRTL_ACCT_PAY.VA_DATE IS '입금마감일';

COMMENT ON COLUMN TBL_OR_VRTL_ACCT_PAY.APP_TIME IS '계좌발급시간';

COMMENT ON COLUMN TBL_OR_VRTL_ACCT_PAY.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_VRTL_ACCT_PAY.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_VRTL_ACCT_PAY.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_VRTL_ACCT_PAY.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_VRTL_ACCT_PAY
	ON TBL_OR_VRTL_ACCT_PAY (
		PAY_NO ASC
	);

/* 통합게시판추가컨텐츠 */
CREATE TABLE TBL_CM_INTG_BOARD_CNTS (
	IMG_SEQ NUMBER NOT NULL, /* 이미지일련번호 */
	TXT_NO NUMBER, /* 게시물번호 */
	IMG_CLS CHAR(7), /* 이미지구분 */
	IMG_URL VARCHAR2(255), /* 이미지 URL */
	PRIR NUMBER, /* 우선순위 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_CM_INTG_BOARD_CNTS IS '통합게시판추가컨텐츠';

COMMENT ON COLUMN TBL_CM_INTG_BOARD_CNTS.IMG_SEQ IS '이미지일련번호';

COMMENT ON COLUMN TBL_CM_INTG_BOARD_CNTS.TXT_NO IS '게시물번호';

COMMENT ON COLUMN TBL_CM_INTG_BOARD_CNTS.IMG_CLS IS '이미지구분';

COMMENT ON COLUMN TBL_CM_INTG_BOARD_CNTS.IMG_URL IS '이미지 URL';

COMMENT ON COLUMN TBL_CM_INTG_BOARD_CNTS.PRIR IS '우선순위';

COMMENT ON COLUMN TBL_CM_INTG_BOARD_CNTS.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_CM_INTG_BOARD_CNTS.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_CM_INTG_BOARD_CNTS.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_CM_INTG_BOARD_CNTS.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_CM_INTG_BOARD_CNTS
	ON TBL_CM_INTG_BOARD_CNTS (
		IMG_SEQ ASC
	);

/* 사용자접속내역 */
CREATE TABLE TBL_AD_LOGIN_HIST (
	LOGIN_SEQ NUMBER NOT NULL, /* 로그인일련번호 */
	USER_NO NUMBER, /* 사용자번호 */
	LOGIN_IP VARCHAR2(15), /* 로그인IP */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_LOGIN_HIST IS '사용자접속내역';

COMMENT ON COLUMN TBL_AD_LOGIN_HIST.LOGIN_SEQ IS '로그인일련번호';

COMMENT ON COLUMN TBL_AD_LOGIN_HIST.USER_NO IS '사용자번호';

COMMENT ON COLUMN TBL_AD_LOGIN_HIST.LOGIN_IP IS '로그인IP';

COMMENT ON COLUMN TBL_AD_LOGIN_HIST.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_LOGIN_HIST.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_LOGIN_HIST.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_LOGIN_HIST.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_AD_LOGIN_HIST
	ON TBL_AD_LOGIN_HIST (
		LOGIN_SEQ ASC
	);

/* 사이트운영정책 */
CREATE TABLE TBL_AD_SITE_POLICY (
	PLCY_NO NUMBER NOT NULL, /* 정책번호 */
	SITE_NO NUMBER NOT NULL, /* 사이트 번호 */
	PLCY_NM VARCHAR2(200), /* 정책명 */
	PLCY_DESC VARCHAR2(200), /* 정책설명 */
	PLCY_TXT CLOB, /* 정책내용 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_SITE_POLICY IS '사이트운영정책';

COMMENT ON COLUMN TBL_AD_SITE_POLICY.PLCY_NO IS '정책번호';

COMMENT ON COLUMN TBL_AD_SITE_POLICY.SITE_NO IS '사이트 번호';

COMMENT ON COLUMN TBL_AD_SITE_POLICY.PLCY_NM IS '정책명';

COMMENT ON COLUMN TBL_AD_SITE_POLICY.PLCY_DESC IS '정책설명';

COMMENT ON COLUMN TBL_AD_SITE_POLICY.PLCY_TXT IS '정책내용';

COMMENT ON COLUMN TBL_AD_SITE_POLICY.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_SITE_POLICY.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_SITE_POLICY.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_SITE_POLICY.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_AD_SITE_POLICY
	ON TBL_AD_SITE_POLICY (
		PLCY_NO ASC
	);

/* 뉴스노출사이트 */
CREATE TABLE TBL_CM_NEWS_SITE (
	TXT_NO NUMBER, /* 게시물번호 */
	SITE_NO NUMBER /* 사이트 번호 */
);

COMMENT ON TABLE TBL_CM_NEWS_SITE IS '뉴스노출사이트';

COMMENT ON COLUMN TBL_CM_NEWS_SITE.TXT_NO IS '게시물번호';

COMMENT ON COLUMN TBL_CM_NEWS_SITE.SITE_NO IS '사이트 번호';

/* 통합게시판 */
CREATE TABLE TBL_CM_INTG_BOARD (
	TXT_NO NUMBER NOT NULL, /* 게시물번호 */
	BOARD_CLCD CHAR(7), /* 게시판분류코드 */
	TITLE VARCHAR(50),
	LNK_URL VARCHAR(200),
	SITE_NO NUMBER, /* 사이트번호 */
	DISP_YN CHAR(1), /* 전시여부 */
	SEASON_CD CHAR(4),
	CLBLTN_NM VARCHAR(50),
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_CM_INTG_BOARD IS '통합게시판';

COMMENT ON COLUMN TBL_CM_INTG_BOARD.TXT_NO IS '게시물번호';

COMMENT ON COLUMN TBL_CM_INTG_BOARD.BOARD_CLCD IS '게시판분류코드';

COMMENT ON COLUMN TBL_CM_INTG_BOARD.SITE_NO IS '사이트번호';

COMMENT ON COLUMN TBL_CM_INTG_BOARD.TITLE IS '제목';

COMMENT ON COLUMN TBL_CM_INTG_BOARD.LNK_URL IS '연결주소';

COMMENT ON COLUMN TBL_CM_INTG_BOARD.DISP_YN IS '전시여부';

COMMENT ON COLUMN TBL_CM_INTG_BOARD.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_CM_INTG_BOARD.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_CM_INTG_BOARD.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_CM_INTG_BOARD.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_CM_INTG_BOARD
	ON TBL_CM_INTG_BOARD (
		TXT_NO ASC
	);

/* 통합게시판추가컨텐츠상품 */
CREATE TABLE TBL_CM_BOARD_GDS (
	IMG_SEQ NUMBER, /* 이미지일련번호 */
	UBI_GDS_NO VARCHAR2(50), /* 상품번호 */
	GDS_NM VARCHAR2(50), /* 상품명 */
	SL_PRC NUMBER, /* 판매가 */
	IMG_URL VARCHAR2(255), /* 이미지 URL */
	LINK_URL VARCHAR2(255), /* 연결 URL */
	PRIR NUMBER /* 우선순위 */
);

COMMENT ON TABLE TBL_CM_BOARD_GDS IS '통합게시판추가컨텐츠상품';

COMMENT ON COLUMN TBL_CM_BOARD_GDS.IMG_SEQ IS '이미지일련번호';

COMMENT ON COLUMN TBL_CM_BOARD_GDS.UBI_GDS_NO IS 'UBI상품번호';

COMMENT ON COLUMN TBL_CM_BOARD_GDS.GDS_NM IS '상품명';

COMMENT ON COLUMN TBL_CM_BOARD_GDS.SL_PRC IS '판매가';

COMMENT ON COLUMN TBL_CM_BOARD_GDS.IMG_URL IS '이미지 URL';

COMMENT ON COLUMN TBL_CM_BOARD_GDS.LINK_URL IS '연결 URL';

COMMENT ON COLUMN TBL_CM_BOARD_GDS.PRIR IS '우선순위';

/* SMS발송이력 */
CREATE TABLE TBL_AD_SND_SMS (
	MNG_NO NUMBER, /* 관리번호 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_AD_SND_SMS IS 'SMS발송이력';

COMMENT ON COLUMN TBL_AD_SND_SMS.MNG_NO IS '관리번호';

COMMENT ON COLUMN TBL_AD_SND_SMS.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_SND_SMS.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_SND_SMS.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_SND_SMS.UPD_DTS IS '수정일시';

/* 전시관리 */
CREATE TABLE TBL_DP_CNTS (
	DISP_CRN_NO NUMBER NOT NULL, /* 전시코너번호 */
	SITE_NO NUMBER, /* 사이트번호 */
	DISP_CRN_CLS CHAR(7), /* 전시코너구분 */
	DISP_CRN_NM VARCHAR2(50), /* 전시코너명 */
	DISP_TXT VARCHAR2(4000), /* 전시내용 */
	DISP_LOC_LNK VARCHAR2(255), /* 전시위치연결 */
	IMG_URL VARCHAR2(255), /* 이미지 URL */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_DP_CNTS IS '전시관리';

COMMENT ON COLUMN TBL_DP_CNTS.DISP_CRN_NO IS '전시코너번호';

COMMENT ON COLUMN TBL_DP_CNTS.SITE_NO IS '사이트번호';

COMMENT ON COLUMN TBL_DP_CNTS.DISP_CRN_CLS IS '전시코너구분';

COMMENT ON COLUMN TBL_DP_CNTS.DISP_CRN_NM IS '전시코너명';

COMMENT ON COLUMN TBL_DP_CNTS.DISP_TXT IS '전시내용';

COMMENT ON COLUMN TBL_DP_CNTS.DISP_LOC_LNK IS '전시위치연결';

COMMENT ON COLUMN TBL_DP_CNTS.IMG_URL IS '이미지 URL';

COMMENT ON COLUMN TBL_DP_CNTS.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_DP_CNTS.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_DP_CNTS.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_DP_CNTS.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_DP_CNTS
	ON TBL_DP_CNTS (
		DISP_CRN_NO ASC
	);
	
	
/* 회원코멘트 */
CREATE TABLE TBL_ME_MEM_CMNT (
	CMNT_NO NUMBER, /* 코멘트번호 */
	MEM_NO NUMBER, /* 회원번호 */
	CMNT_TXT VARCHAR2(500), /* 코멘트내용 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

CREATE UNIQUE INDEX TBL_ME_MEM_CMNT
	ON TBL_ME_MEM_CMNT (
		CMNT_NO ASC
	);
  
  ALTER TABLE TBL_ME_MEM_CMNT
	ADD
		CONSTRAINT PK_TBL_ME_MEM_CMNT
		PRIMARY KEY (
			CMNT_NO
		);

COMMENT ON TABLE TBL_ME_MEM_CMNT IS '회원코멘트';

COMMENT ON COLUMN TBL_ME_MEM_CMNT.CMNT_NO IS '코멘트번호';

COMMENT ON COLUMN TBL_ME_MEM_CMNT.MEM_NO IS '회원번호';

COMMENT ON COLUMN TBL_ME_MEM_CMNT.CMNT_TXT IS '코멘트내용';

COMMENT ON COLUMN TBL_ME_MEM_CMNT.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_ME_MEM_CMNT.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_ME_MEM_CMNT.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_ME_MEM_CMNT.UPD_DTS IS '수정일시';

/* 메인관리 */
CREATE TABLE TBL_CM_MAIN (
	MAIN_NO NUMBER, /* 메인번호 */
	IMG_URL VARCHAR2(255), /* 이미지 URL */
	LNK_URL VARCHAR2(255), /* 연결URL */
	TXT VARCHAR2(255), /* 내용 */
	SITE_NO NUMBER, /* 사이트번호 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_CM_MAIN IS '메인관리';

COMMENT ON COLUMN TBL_CM_MAIN.MAIN_NO IS '메인번호';

COMMENT ON COLUMN TBL_CM_MAIN.IMG_URL IS '이미지 URL';

COMMENT ON COLUMN TBL_CM_MAIN.LNK_URL IS '연결URL';

COMMENT ON COLUMN TBL_CM_MAIN.TXT IS '내용';

COMMENT ON COLUMN TBL_CM_MAIN.SITE_NO IS '사이트번호';

COMMENT ON COLUMN TBL_CM_MAIN.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_CM_MAIN.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_CM_MAIN.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_CM_MAIN.UPD_DTS IS '수정일시';

/* feature관리 */
CREATE TABLE TBL_CM_FEATURE (
	FEATURE_NO NUMBER, /* 피쳐번호 */
	SEX CHAR(1), /* 성별 */
	IMG_URL VARCHAR2(255), /* 이미지 URL */
	LNK_URL VARCHAR2(255), /* 연결URL */
	TXT VARCHAR2(255), /* 내용 */
	SITE_NO NUMBER, /* 사이트번호 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_CM_FEATURE IS 'feature관리';

COMMENT ON COLUMN TBL_CM_FEATURE.FEATURE_NO IS '피쳐번호';

COMMENT ON COLUMN TBL_CM_FEATURE.SEX IS '성별';

COMMENT ON COLUMN TBL_CM_FEATURE.IMG_URL IS '이미지 URL';

COMMENT ON COLUMN TBL_CM_FEATURE.LNK_URL IS '연결URL';

COMMENT ON COLUMN TBL_CM_FEATURE.TXT IS '내용';

COMMENT ON COLUMN TBL_CM_FEATURE.SITE_NO IS '사이트번호';

COMMENT ON COLUMN TBL_CM_FEATURE.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_CM_FEATURE.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_CM_FEATURE.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_CM_FEATURE.UPD_DTS IS '수정일시';

/* 주문메모 */
CREATE TABLE TBL_OR_ORD_MEMO (
	ORD_NO NUMBER NOT NULL, /* 주문번호 */
	MEMO_NO NUMBER NOT NULL, /* 덧글번호 */
	MEMO_TXT VARCHAR2(4000), /* 덧글내용 */
	WRTR_CLS CHAR(7), /* 작성자구분 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_OR_ORD_MEMO IS '주문메모';

COMMENT ON COLUMN TBL_OR_ORD_MEMO.ORD_NO IS '상담번호';

COMMENT ON COLUMN TBL_OR_ORD_MEMO.MEMO_NO IS '덧글번호';

COMMENT ON COLUMN TBL_OR_ORD_MEMO.MEMO_TXT IS '덧글내용';

COMMENT ON COLUMN TBL_OR_ORD_MEMO.WRTR_CLS IS '작성자구분';

COMMENT ON COLUMN TBL_OR_ORD_MEMO.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_OR_ORD_MEMO.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_OR_ORD_MEMO.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_OR_ORD_MEMO.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_OR_ORD_MEMO
	ON TBL_OR_ORD_MEMO (
		ORD_NO ASC,
		MEMO_NO ASC
	);

ALTER TABLE TBL_OR_ORD_MEMO
	ADD
		CONSTRAINT PK_TBL_CM_CNSL_MEMO2
		PRIMARY KEY (
			ORD_NO,
			MEMO_NO
		);

ALTER TABLE TBL_OR_ORD_MEMO
	ADD
		CONSTRAINT FK_TBL_OR_ORD_TO_TBL_OR_ORD_MEMO
		FOREIGN KEY (
			ORD_NO
		)
		REFERENCES TBL_OR_ORD (
			ORD_NO
		);
		
/* 뉴스추가컨텐츠 */
CREATE TABLE TBL_CM_NEWS_CONT (
	ADD_CONT_NO NUMBER NOT NULL, /* 추가컨텐츠번호 */
	TXT_NO NUMBER, /* 게시물번호 */
	ADD_CONT_TYPE CHAR(7), /* 추가컨텐츠타입 */
	ADD_CONT_ADDR VARCHAR2(255) /* 추가컨텐츠주소 */
);

COMMENT ON TABLE TBL_CM_NEWS_CONT IS '뉴스추가컨텐츠';

COMMENT ON COLUMN TBL_CM_NEWS_CONT.ADD_CONT_NO IS '추가컨텐츠번호';

COMMENT ON COLUMN TBL_CM_NEWS_CONT.TXT_NO IS '게시물번호';

COMMENT ON COLUMN TBL_CM_NEWS_CONT.ADD_CONT_TYPE IS '추가컨텐츠타입';

COMMENT ON COLUMN TBL_CM_NEWS_CONT.ADD_CONT_ADDR IS '추가컨텐츠주소';
		
		
		

  CREATE TABLE "TBL_AD_ZIP_CD" 
   (	"LAW_DONG_CD" VARCHAR2(10 BYTE), 
	"SIDO_NM" VARCHAR2(20 BYTE), 
	"SIGUNGU_NM" VARCHAR2(20 BYTE), 
	"LAW_EMD_NM" VARCHAR2(20 BYTE), 
	"LAW_LI_NM" VARCHAR2(20 BYTE), 
	"SAN_YN" VARCHAR2(1 BYTE), 
	"JIBUN_BON" NUMBER(4,0), 
	"JIBUN_BU" NUMBER(4,0), 
	"LOAD_CD" VARCHAR2(12 BYTE), 
	"LOAD_NM" VARCHAR2(80 BYTE), 
	"UNDER_YN" VARCHAR2(1 BYTE), 
	"BUILD_BON" NUMBER(5,0), 
	"BUILD_BU" NUMBER(5,0), 
	"BUILD_NM" VARCHAR2(40 BYTE), 
	"BUILD_NM_DETAIL" VARCHAR2(100 BYTE), 
	"BUILD_NO" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"EMD_NO" VARCHAR2(2 BYTE), 
	"ADM_DONG_CD" VARCHAR2(10 BYTE), 
	"ADM_DONG_NM" VARCHAR2(20 BYTE), 
	"ZIP_CD" VARCHAR2(6 BYTE), 
	"ZIP_NO" VARCHAR2(3 BYTE), 
	"MUCH_DELIVE_NM" VARCHAR2(40 BYTE), 
	"REASON_MOVE_CD" VARCHAR2(2 BYTE), 
	"CHANGE_DATE" VARCHAR2(8 BYTE), 
	"PRE_CHANGE_LOAD" VARCHAR2(25 BYTE), 
	"SIGUNGU_BUILD_NM" VARCHAR2(200 BYTE), 
	"APART_YN" VARCHAR2(1 BYTE)
   ) 

   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."LAW_DONG_CD" IS '법정동코드';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."SIDO_NM" IS '시도명';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."SIGUNGU_NM" IS '시군구명';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."LAW_EMD_NM" IS '법정읍면동명';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."LAW_LI_NM" IS '법정리명';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."SAN_YN" IS '산여부 0:토지,1:산';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."JIBUN_BON" IS '지번본번';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."JIBUN_BU" IS '지번부번';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."LOAD_CD" IS '도로명코드 시군구(5)+도로명번호(7)';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."LOAD_NM" IS '도로명';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."UNDER_YN" IS '지하여부 0:지상, 1:지하, 2:공중';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."BUILD_BON" IS '건물본번';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."BUILD_BU" IS '건물부번';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."BUILD_NM" IS '건축물대장 건물명';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."BUILD_NM_DETAIL" IS '상세건물명';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."BUILD_NO" IS '건물관리번호 고유식별컬럼';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."EMD_NO" IS '읍면동일련번호';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."ADM_DONG_CD" IS '행정동코드';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."ADM_DONG_NM" IS '행정동명';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."ZIP_CD" IS '우편번호';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."ZIP_NO" IS '우편일련번호';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."MUCH_DELIVE_NM" IS '다량배달처명';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."REASON_MOVE_CD" IS '이동사유코드';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."CHANGE_DATE" IS '변경일자';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."PRE_CHANGE_LOAD" IS '변경전도로명주소';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."SIGUNGU_BUILD_NM" IS '시군구용 건물명 참고용';
 
   COMMENT ON COLUMN "TBL_AD_ZIP_CD"."APART_YN" IS '공동주택여부 0:비공동주택, 1:공동주택';

   
/* 채용공고 */
CREATE TABLE TBL_CM_WORKS_WITHUS (
	WITHUS_SEQ NUMBER NOT NULL, /* 공고번호 */
	WITHUS_STAT CHAR(7), /* 상태 */
	WITHUS_CLS VARCHAR2(50) NOT NULL, /* 구분 */
	WITHUS_AREA VARCHAR2(50), /* 지역 */
	WITHUS_CL VARCHAR2(50), /* 모집분야 */
	STR_DTS DATE, /* 시작일시 */
	END_DTS DATE, /* 종료일시 */
	DTL_DESC CLOB, /* 상세설명 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_CM_WORKS_WITHUS IS '채용공고';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS.WITHUS_SEQ IS '공고번호';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS.WITHUS_STAT IS '상태';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS.WITHUS_CLS IS '구분';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS.WITHUS_AREA IS '지역';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS.WITHUS_CL IS '모집분야';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS.STR_DTS IS '시작일시';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS.END_DTS IS '종료일시';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS.DTL_DESC IS '상세설명';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX PK_TBL_CM_WORKS_WITHUS
	ON TBL_CM_WORKS_WITHUS (
		WITHUS_SEQ ASC
	);

ALTER TABLE TBL_CM_WORKS_WITHUS
	ADD
		CONSTRAINT PK_TBL_CM_WORKS_WITHUS
		PRIMARY KEY (
			WITHUS_SEQ
		);

/* 채용공고노출사이트 */
CREATE TABLE TBL_CM_WORKS_WITHUS_SITE (
	WITHUS_SEQ NUMBER, /* 공고번호 */
	SITE_NO NUMBER /* 사이트 번호 */
);

COMMENT ON TABLE TBL_CM_WORKS_WITHUS_SITE IS '채용공고노출사이트';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS_SITE.WITHUS_SEQ IS '공고번호';

COMMENT ON COLUMN TBL_CM_WORKS_WITHUS_SITE.SITE_NO IS '사이트 번호';

ALTER TABLE TBL_CM_WORKS_WITHUS_SITE
	ADD
		CONSTRAINT FK_WITHUS_TO_WITHUS_SITE
		FOREIGN KEY (
			WITHUS_SEQ
		)
		REFERENCES TBL_CM_WORKS_WITHUS (
			WITHUS_SEQ
		); 
		
		
/* 방문자통계 */
CREATE TABLE TBL_ST_VISIT (
	CONN_SEQ NUMBER NOT NULL, /* 접속통계번호 */
	CONN_DTM DATE, /* 접속일시 */
	CONN_IP_ADDR VARCHAR2(15), /* 접속아이피 */
	CONN_BRND VARCHAR2(50), /* 브랜드 */
	CONN_DOMAIN VARCHAR2(255), /* 접속경로 */
	CONN_BRWS VARCHAR2(50), /* 브라우저 */
	CONN_OS VARCHAR2(50), /* OS */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_ST_VISIT IS '방문자통계';

COMMENT ON COLUMN TBL_ST_VISIT.CONN_SEQ IS '접속통계번호';

COMMENT ON COLUMN TBL_ST_VISIT.CONN_DTM IS '접속일시';

COMMENT ON COLUMN TBL_ST_VISIT.CONN_IP_ADDR IS '접속아이피';

COMMENT ON COLUMN TBL_ST_VISIT.CONN_BRND IS '브랜드';

COMMENT ON COLUMN TBL_ST_VISIT.CONN_DOMAIN IS '접속경로';

COMMENT ON COLUMN TBL_ST_VISIT.CONN_BRWS IS '브라우저';

COMMENT ON COLUMN TBL_ST_VISIT.CONN_OS IS 'OS';

COMMENT ON COLUMN TBL_ST_VISIT.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_ST_VISIT.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_ST_VISIT.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_ST_VISIT.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX UK_ST_VISIT
	ON TBL_ST_VISIT (
		CONN_SEQ ASC
	);

ALTER TABLE TBL_ST_VISIT
	ADD
		CONSTRAINT PK_TBL_ST_VISIT
		PRIMARY KEY (
			CONN_SEQ
		);
		
		
/* 칼하트라디오 */
CREATE TABLE TBL_DP_RADIO (
	RADIO_NO NUMBER NOT NULL, /* 라디오번호 */
	DISP_YN CHAR(1), /* 전시여부 */
	BAN_IMG_URL VARCHAR2(255), /* 배너이미지 URL */
	CV_IMG_URL VARCHAR2(255), /* 커버이미지 URL */
	BG_IMG_URL VARCHAR2(255), /* 배경이미지 URL */
	RADIO_LINK VARCHAR2(255), /* 라디오링크 */
	RADIO_TITLE VARCHAR2(50), /* 제목 */
	RADIO_ARTIST VARCHAR2(50), /* 아티스트 */
	RADIO_INFO VARCHAR2(4000), /* 정보 */
	RADIO_ARTIST_INFO VARCHAR2(4000), /* 정보 */
	RADIO_TRACK_LIST VARCHAR2(4000), /* 트랙리스트 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_DP_RADIO IS '칼하트라디오';

COMMENT ON COLUMN TBL_DP_RADIO.RADIO_NO IS '라디오번호';

COMMENT ON COLUMN TBL_DP_RADIO.DISP_YN IS '전시여부';

COMMENT ON COLUMN TBL_DP_RADIO.BAN_IMG_URL IS '배너이미지 URL';

COMMENT ON COLUMN TBL_DP_RADIO.CV_IMG_URL IS '커버이미지 URL';

COMMENT ON COLUMN TBL_DP_RADIO.BG_IMG_URL IS '배경이미지 URL';

COMMENT ON COLUMN TBL_DP_RADIO.RADIO_LINK IS '라디오링크';

COMMENT ON COLUMN TBL_DP_RADIO.RADIO_TITLE IS '제목';

COMMENT ON COLUMN TBL_DP_RADIO.RADIO_ARTIST IS '아티스트';

COMMENT ON COLUMN TBL_DP_RADIO.RADIO_INFO IS '정보';

COMMENT ON COLUMN TBL_DP_RADIO.RADIO_ARTIST_INFO IS '정보';

COMMENT ON COLUMN TBL_DP_RADIO.RADIO_TRACK_LIST IS '트랙리스트';

COMMENT ON COLUMN TBL_DP_RADIO.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_DP_RADIO.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_DP_RADIO.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_DP_RADIO.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX UQ_TBL_DP_RADIO
	ON UQ_TBL_DP_RADIO (
		RADIO_NO ASC
	);

ALTER TABLE TBL_DP_RADIO
	ADD
		CONSTRAINT PK_TBL_DP_RADIO
		PRIMARY KEY (
			RADIO_NO
		);

/* OBEY_Awareness */
CREATE TABLE TBL_DP_AWNES (
	AWNES_NO NUMBER NOT NULL, /* 전시번호 */
	DISP_YN CHAR(1), /* 전시여부 */
	DTL_TXT VARCHAR2(4000), /* 상세내용 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_DP_AWNES IS 'OBEY_Awareness';

COMMENT ON COLUMN TBL_DP_AWNES.AWNES_NO IS '전시번호';

COMMENT ON COLUMN TBL_DP_AWNES.DISP_YN IS '전시여부';

COMMENT ON COLUMN TBL_DP_AWNES.DTL_TXT IS '상세내용';

COMMENT ON COLUMN TBL_DP_AWNES.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_DP_AWNES.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_DP_AWNES.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_DP_AWNES.UPD_DTS IS '수정일시';

CREATE UNIQUE INDEX UQ_TBL_DP_AWNES
	ON UQ_TBL_DP_AWNES (
		AWNES_NO ASC
	);

ALTER TABLE TBL_DP_AWNES
	ADD
		CONSTRAINT PK_TBL_DP_AWNES
		PRIMARY KEY (
			AWNES_NO
		);

/* OBEY_AWARENESS_컨텐츠 */
CREATE TABLE TBL_DP_AWNES_CONT (
	AWNES_NO NUMBER, /* 전시번호 */
	CONT_CLS CHAR(7), /* 컨텐츠구분 */
	CONT_URL VARCHAR2(255), /* 컨텐츠URL */
	IMG_URL VARCHAR2(255), /* 컨텐츠URL */
	PRIR NUMBER, /* 우선순위 */
	REGR_NO NUMBER NOT NULL, /* 등록자 */
	REG_DTS DATE DEFAULT sysdate NOT NULL, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE /* 수정일시 */
);

COMMENT ON TABLE TBL_DP_AWNES_CONT IS 'OBEY_AWARENESS_컨텐츠';

COMMENT ON COLUMN TBL_DP_AWNES_CONT.AWNES_NO IS '전시번호';

COMMENT ON COLUMN TBL_DP_AWNES_CONT.CONT_CLS IS '컨텐츠구분';

COMMENT ON COLUMN TBL_DP_AWNES_CONT.CONT_URL IS '컨텐츠URL';

COMMENT ON COLUMN TBL_DP_AWNES_CONT.IMG_URL IS '이미지URL';

COMMENT ON COLUMN TBL_DP_AWNES_CONT.PRIR IS '우선순위';

COMMENT ON COLUMN TBL_DP_AWNES_CONT.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_DP_AWNES_CONT.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_DP_AWNES_CONT.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_DP_AWNES_CONT.UPD_DTS IS '수정일시';

ALTER TABLE TBL_DP_AWNES_CONT
	ADD
		CONSTRAINT FK_TBL_DP_AWNES
		FOREIGN KEY (
			AWNES_NO
		)
		REFERENCES TBL_DP_AWNES (
			AWNES_NO
		);		
		
		
		

		
		
		
		
/* 사이트 시즌설정 */
CREATE TABLE TBL_AD_CATE_SEASON (
	SEASON_SEQ NUMBER NOT NULL, /* 시즌 시퀀스 */
	SITE_NO NUMBER, /* 사이트 번호 */
	SEASON_CD VARCHAR2(12), /* 시즌코드 */
	SEASON_GUBUN CHAR(7), /* 시즌구분 코드 */
	SEASON_CD_DISP VARCHAR2(30), /* 시즌코드명 별칭 */
	SEASON_START DATE, /* 시즌 시작시간 */
	SEASON_END DATE, /* 시즌 종료시간 */
	DISP_YN CHAR(1), /* 노출여부 */
	USE_YN CHAR(1), /* 사용여부 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE, /* 수정일시 */
	TOP_YN CHAR(1) /* 우선노출 여부 */
);

COMMENT ON TABLE TBL_AD_CATE_SEASON IS '사이트 시즌설정';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.SEASON_SEQ IS '시즌 시퀀스';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.SITE_NO IS '사이트 번호';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.SEASON_CD IS '시즌코드';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.SEASON_GUBUN IS '시즌구분 코드';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.+ CM01401 시즌1 IS '+ CM01401 시즌1';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.+ CM01402 시즌2 IS '+ CM01402 시즌2';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.+ CM01403 OUTLET IS '+ CM01403 OUTLET';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.SEASON_CD_DISP IS '시즌코드명 별칭';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.SEASON_START IS '시즌 시작시간';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.SEASON_END IS '시즌 종료시간';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.DISP_YN IS '노출여부';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.USE_YN IS '사용여부';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.UPD_DTS IS '수정일시';

COMMENT ON COLUMN TBL_AD_CATE_SEASON.TOP_YN IS '우선노출 여부';

CREATE UNIQUE INDEX PK_TBL_AD_CATE_SEASON
	ON TBL_AD_CATE_SEASON (
		SEASON_SEQ ASC
	);

ALTER TABLE TBL_AD_CATE_SEASON
	ADD
		CONSTRAINT PK_TBL_AD_CATE_SEASON
		PRIMARY KEY (
			SEASON_SEQ
		);
		
		
		
		
		
		
		
/* 시즌 카테고리 설정 */
CREATE TABLE TBL_AD_CATE_CONFIG (
	SEASON_SEQ NUMBER, /* 시즌 시퀀스 */
	CATE_DEPTH_1 CHAR(7), /* 카테고리 1뎁스 */
	CATE_DEPTH_2 VARCHAR2(500), /* 카테고리 2뎁스 */
	CATE_DEPTH_3 VARCHAR2(500), /* 카테고리 3뎁스 */
	NA_DISP_YN CHAR(1), /* NEW_ARRIVAL 노출여부 */
	USE_YN CHAR(1), /* 사용여부 */
	REGR_NO NUMBER, /* 등록자 */
	REG_DTS DATE, /* 등록일시 */
	UPDR_NO NUMBER, /* 수정자 */
	UPD_DTS DATE, /* 수정일시 */
	NA_DISP_NM VARCHAR2(100), /* NEW ARRIVAL 화면 표시명 */
	
);

COMMENT ON TABLE TBL_AD_CATE_CONFIG IS '시즌 카테고리 설정';

COMMENT ON COLUMN TBL_AD_CATE_CONFIG.SEASON_SEQ IS '시즌 시퀀스';

COMMENT ON COLUMN TBL_AD_CATE_CONFIG.CATE_DEPTH_1 IS '카테고리 1뎁스';

COMMENT ON COLUMN TBL_AD_CATE_CONFIG.CATE_DEPTH_2 IS '카테고리 2뎁스';

COMMENT ON COLUMN TBL_AD_CATE_CONFIG.CATE_DEPTH_3 IS '카테고리 3뎁스';

COMMENT ON COLUMN TBL_AD_CATE_CONFIG.NA_DISP_YN IS 'NEW_ARRIVAL 노출여부';

COMMENT ON COLUMN TBL_AD_CATE_CONFIG.USE_YN IS '사용여부';

COMMENT ON COLUMN TBL_AD_CATE_CONFIG.REGR_NO IS '등록자';

COMMENT ON COLUMN TBL_AD_CATE_CONFIG.REG_DTS IS '등록일시';

COMMENT ON COLUMN TBL_AD_CATE_CONFIG.UPDR_NO IS '수정자';

COMMENT ON COLUMN TBL_AD_CATE_CONFIG.UPD_DTS IS '수정일시';

COMMENT ON COLUMN TBL_AD_CATE_CONFIG.NA_DISP_NM IS 'NEW ARRIVAL 화면 표시명';
